// Line 13, Grand Terminus. Block signals with a timetable, generated with tools/lab/blockgen.ts
// (plan in tools/lab/blockplan.ts) and picked by hand.

import type { Stop } from "../levels";

export const GRAND_TERMINUS: Stop[] = [
  {
    id: "13-1",
    name: "Concourse",
    rows: [".........", ".........", ".........", "HHHHHH.HH", "HHHHHH.HH", ".........", "..H....H.", "........."],
    depots: [
      { at: [5, 0], dir: "S", trains: [0, 0], start: 0, every: 3 },
      { at: [1, 7], dir: "N", trains: [1, 1], start: 3, every: 5 },
      { at: [8, 1], dir: "W", trains: [2, 2], start: 3, every: 4 },
    ],
    stations: [{ at: [6, 7], dir: "N", color: 0 }, { at: [3, 0], dir: "S", color: 1 }, { at: [3, 7], dir: "N", color: 2 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 40,
    solution: {
      paths: [
        [[5, 0], [5, 1], [6, 1], [6, 2], [6, 3], [6, 4], [6, 5], [6, 6], [6, 7]],
        [
          [1, 7],
          [1, 6],
          [1, 5],
          [2, 5],
          [3, 5],
          [4, 5],
          [5, 5],
          [6, 5],
          [6, 4],
          [6, 3],
          [6, 2],
          [6, 1],
          [5, 1],
          [4, 1],
          [3, 1],
          [3, 0],
        ],
        [
          [8, 1],
          [7, 1],
          [7, 0],
          [6, 0],
          [6, 1],
          [6, 2],
          [6, 3],
          [6, 4],
          [6, 5],
          [6, 6],
          [5, 6],
          [4, 6],
          [3, 6],
          [3, 7],
        ],
      ],
      stops: [[5, 5]],
      facing: [[5, 5, "E"]],
      lamps: [[6, 6, 0]],
      levers: [[5, 1, "W"], [6, 1, "W"], [6, 5, "S"], [6, 6, "S"]],
      stems: [[5, 1, "E"], [6, 1, "S"], [6, 5, "N"], [6, 6, "N"]],
    },
  },
  {
    id: "13-2",
    name: "Ticket Hall",
    rows: ["HHHHHHH.HHHHH", "H.HHHH...HH.H", "H...........H", "H.HH.HHHHHH.H", "HHHH.HHHHHHHH"],
    depots: [
      { at: [0, 1], dir: "E", trains: [0, 0, 0], start: 0, every: 4 },
      { at: [12, 3], dir: "W", trains: [1, 1], start: 4, every: 4 },
      { at: [7, 0], dir: "S", trains: [3], start: 2, every: 4 },
    ],
    stations: [{ at: [12, 1], dir: "W", color: 0 }, { at: [0, 3], dir: "E", color: 1 }, { at: [4, 4], dir: "N", color: 3 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 44,
    solution: {
      paths: [
        [
          [0, 1],
          [1, 1],
          [1, 2],
          [2, 2],
          [3, 2],
          [4, 2],
          [5, 2],
          [6, 2],
          [7, 2],
          [8, 2],
          [9, 2],
          [10, 2],
          [11, 2],
          [11, 1],
          [12, 1],
        ],
        [
          [12, 3],
          [11, 3],
          [11, 2],
          [10, 2],
          [9, 2],
          [8, 2],
          [8, 1],
          [7, 1],
          [6, 1],
          [6, 2],
          [5, 2],
          [4, 2],
          [3, 2],
          [2, 2],
          [1, 2],
          [1, 3],
          [0, 3],
        ],
        [[7, 0], [7, 1], [6, 1], [6, 2], [5, 2], [4, 2], [4, 3], [4, 4]],
      ],
      stops: [[6, 1], [8, 1], [7, 2]],
      facing: [[6, 1, "S"], [8, 1, "S"]],
      lamps: [[4, 2, 1]],
      levers: [[1, 2, "S"], [4, 2, "W"], [6, 2, "E"], [8, 2, "N"], [11, 2, "N"]],
      stems: [[1, 2, "E"], [4, 2, "E"], [6, 2, "W"], [8, 2, "E"], [11, 2, "W"], [7, 1, "W"]],
    },
  },
  {
    id: "13-3",
    name: "Left Luggage",
    rows: [".........", ".....H...", ".........", "HHHHHH.HH", "HHHHHH.HH", "HHHHHH.HH", ".........", "........."],
    depots: [
      { at: [4, 0], dir: "S", trains: [0, 0, 0], start: 0, every: 5 },
      { at: [7, 7], dir: "N", trains: [1], start: 4, every: 5, goods: true },
      { at: [8, 2], dir: "W", trains: [2, 2], start: 2, every: 4 },
    ],
    stations: [{ at: [2, 7], dir: "N", color: 0 }, { at: [0, 1], dir: "E", color: 1 }, { at: [0, 7], dir: "E", color: 2 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 52,
    solution: {
      paths: [
        [
          [4, 0],
          [4, 1],
          [4, 2],
          [5, 2],
          [6, 2],
          [6, 3],
          [6, 4],
          [6, 5],
          [6, 6],
          [5, 6],
          [4, 6],
          [3, 6],
          [2, 6],
          [2, 7],
        ],
        [
          [7, 7],
          [7, 6],
          [6, 6],
          [6, 5],
          [6, 4],
          [6, 3],
          [6, 2],
          [5, 2],
          [4, 2],
          [4, 1],
          [3, 1],
          [3, 0],
          [2, 0],
          [2, 1],
          [1, 1],
          [0, 1],
        ],
        [
          [8, 2],
          [7, 2],
          [7, 1],
          [6, 1],
          [6, 2],
          [6, 3],
          [6, 4],
          [6, 5],
          [6, 6],
          [5, 6],
          [4, 6],
          [3, 6],
          [2, 6],
          [1, 6],
          [1, 7],
          [0, 7],
        ],
      ],
      stops: [[7, 6]],
      facing: [[7, 6, "W"]],
      lamps: [[2, 6, 0]],
      levers: [[4, 1, "W"], [6, 2, "W"], [6, 6, "W"], [2, 6, "S"]],
      stems: [[4, 1, "S"], [6, 2, "S"], [6, 6, "N"], [2, 6, "E"]],
    },
  },
  {
    id: "13-4",
    name: "Departure Board",
    rows: ["HHHHHHHHHHHHH", "H.HHHHHHHHH.H", "H...........H", "H.HHHH...HH.H", "HHHHHHHHHHHHH"],
    depots: [
      { at: [0, 1], dir: "E", trains: [0, 0, 0], start: 0, every: 4 },
      { at: [12, 3], dir: "W", trains: [1, 1, 1], start: 3, every: 3 },
    ],
    stations: [{ at: [12, 1], dir: "W", color: 0 }, { at: [0, 3], dir: "E", color: 1 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 44,
    solution: {
      paths: [
        [
          [0, 1],
          [1, 1],
          [1, 2],
          [2, 2],
          [3, 2],
          [4, 2],
          [5, 2],
          [6, 2],
          [6, 3],
          [7, 3],
          [8, 3],
          [8, 2],
          [9, 2],
          [10, 2],
          [11, 2],
          [11, 1],
          [12, 1],
        ],
        [
          [12, 3],
          [11, 3],
          [11, 2],
          [10, 2],
          [9, 2],
          [8, 2],
          [7, 2],
          [6, 2],
          [5, 2],
          [4, 2],
          [3, 2],
          [2, 2],
          [1, 2],
          [1, 3],
          [0, 3],
        ],
      ],
      stops: [[7, 2], [6, 3], [8, 3]],
      facing: [[6, 3, "N"], [8, 3, "N"]],
      levers: [[1, 2, "S"], [6, 2, "S"], [8, 2, "W"], [11, 2, "N"]],
      stems: [[1, 2, "E"], [6, 2, "W"], [8, 2, "E"], [11, 2, "W"]],
    },
  },
  {
    id: "13-5",
    name: "Platform Nine",
    rows: [".........", "....H....", ".........", "HH.HHHH.H", "HH.HHHH.H", ".........", ".........", "........."],
    depots: [
      { at: [0, 2], dir: "E", trains: [0, 0], start: 0, every: 3 },
      { at: [6, 7], dir: "N", trains: [1, 1], start: 1, every: 3 },
      { at: [8, 1], dir: "W", trains: [2, 2], start: 4, every: 3 },
      { at: [4, 7], dir: "N", trains: [3], start: 1, every: 4 },
    ],
    stations: [
      { at: [8, 6], dir: "W", color: 0 },
      { at: [5, 0], dir: "S", color: 1 },
      { at: [0, 6], dir: "E", color: 2 },
      { at: [2, 0], dir: "S", color: 3 },
    ],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 44,
    solution: {
      paths: [
        [
          [0, 2],
          [1, 2],
          [1, 1],
          [2, 1],
          [3, 1],
          [3, 2],
          [4, 2],
          [5, 2],
          [6, 2],
          [7, 2],
          [7, 3],
          [7, 4],
          [7, 5],
          [7, 6],
          [8, 6],
        ],
        [[6, 7], [6, 6], [6, 5], [7, 5], [7, 4], [7, 3], [7, 2], [6, 2], [6, 1], [5, 1], [5, 0]],
        [
          [8, 1],
          [7, 1],
          [7, 0],
          [6, 0],
          [6, 1],
          [6, 2],
          [7, 2],
          [7, 3],
          [7, 4],
          [7, 5],
          [6, 5],
          [5, 5],
          [4, 5],
          [4, 6],
          [3, 6],
          [2, 6],
          [1, 6],
          [0, 6],
        ],
        [[4, 7], [4, 6], [4, 5], [3, 5], [2, 5], [2, 4], [2, 3], [2, 2], [2, 1], [2, 0]],
      ],
      stops: [[6, 6]],
      facing: [[6, 6, "N"]],
      lamps: [[7, 5, 0]],
      levers: [[6, 2, "N"], [7, 5, "S"], [6, 5, "W"], [6, 1, "W"], [4, 5, "W"], [4, 6, "W"]],
      stems: [[6, 2, "E"], [7, 5, "N"], [6, 5, "E"], [6, 1, "S"], [4, 5, "S"], [4, 6, "N"]],
    },
  },
  {
    id: "13-6",
    name: "Station Master",
    rows: [".........", ".T....T..", ".........", "^^^^^^^^^", "^^^^^^^^^", ".........", ".........", "........."],
    depots: [
      { at: [5, 0], dir: "S", trains: [0, 0, 0], start: 0, every: 3 },
      { at: [0, 6], dir: "E", trains: [1, 1], start: 3, every: 5 },
      { at: [0, 2], dir: "E", trains: [2, 2], start: 3, every: 4 },
    ],
    stations: [{ at: [8, 6], dir: "W", color: 0 }, { at: [8, 2], dir: "W", color: 1 }, { at: [5, 7], dir: "N", color: 2 }],
    tunnels: [[[4, 3], [4, 4]]],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 39,
    solution: {
      paths: [
        [[5, 0], [5, 1], [5, 2], [4, 2], [4, 3], [4, 4], [4, 5], [5, 5], [6, 5], [7, 5], [7, 6], [8, 6]],
        [[0, 6], [1, 6], [1, 5], [2, 5], [3, 5], [4, 5], [4, 4], [4, 3], [4, 2], [5, 2], [6, 2], [7, 2], [8, 2]],
        [
          [0, 2],
          [1, 2],
          [2, 2],
          [2, 1],
          [2, 0],
          [3, 0],
          [4, 0],
          [4, 1],
          [4, 2],
          [4, 3],
          [4, 4],
          [4, 5],
          [5, 5],
          [5, 6],
          [5, 7],
        ],
      ],
      stops: [[3, 5]],
      facing: [[3, 5, "E"]],
      lamps: [[5, 5, 0]],
      levers: [[5, 2, "E"], [4, 2, "E"], [4, 5, "E"], [5, 5, "E"]],
      stems: [[5, 2, "W"], [4, 2, "S"], [4, 5, "N"], [5, 5, "W"]],
    },
  },
  {
    id: "13-7",
    name: "Great Roof",
    rows: ["HHHH.HHHHHHHH", "H.HH.H...HH.H", "H...........H", "H.HHHH.HHHH.H", "HHHHHH.HHHHHH"],
    depots: [
      { at: [0, 1], dir: "E", trains: [0, 0, 0], start: 0, every: 3 },
      { at: [12, 3], dir: "W", trains: [1, 1, 1], start: 1, every: 3 },
      { at: [6, 4], dir: "N", trains: [2], start: 4, every: 4 },
    ],
    stations: [{ at: [12, 1], dir: "W", color: 0 }, { at: [0, 3], dir: "E", color: 1 }, { at: [4, 0], dir: "S", color: 2 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 65,
    solution: {
      paths: [
        [
          [0, 1],
          [1, 1],
          [1, 2],
          [2, 2],
          [3, 2],
          [4, 2],
          [5, 2],
          [6, 2],
          [7, 2],
          [8, 2],
          [9, 2],
          [10, 2],
          [11, 2],
          [11, 1],
          [12, 1],
        ],
        [
          [12, 3],
          [11, 3],
          [11, 2],
          [10, 2],
          [9, 2],
          [8, 2],
          [7, 2],
          [6, 2],
          [5, 2],
          [4, 2],
          [3, 2],
          [2, 2],
          [1, 2],
          [1, 3],
          [0, 3],
        ],
        [[6, 4], [6, 3], [6, 2], [5, 2], [4, 2], [4, 1], [4, 0]],
      ],
      stops: [[6, 3], [11, 3]],
      facing: [[6, 3, "N"], [11, 3, "N"]],
      lamps: [[4, 2, 1]],
      levers: [[1, 2, "S"], [4, 2, "W"], [6, 2, "E"], [11, 2, "N"]],
      stems: [[1, 2, "E"], [4, 2, "E"], [6, 2, "W"], [11, 2, "W"]],
    },
  },
  {
    id: "13-8",
    name: "Grand Terminus",
    rows: [".........", ".........", ".........", "HHHHHHH.H", "HHHHHHH.H", ".........", ".......H.", "........."],
    depots: [
      { at: [0, 1], dir: "E", trains: [0, 0, 0], start: 0, every: 3 },
      { at: [2, 7], dir: "N", trains: [1, 1], start: 1, every: 5 },
      { at: [8, 1], dir: "W", trains: [2, 2], start: 4, every: 3 },
      { at: [0, 6], dir: "E", trains: [3, 3], start: 3, every: 5 },
    ],
    stations: [
      { at: [6, 7], dir: "N", color: 0 },
      { at: [4, 0], dir: "S", color: 1 },
      { at: [4, 7], dir: "N", color: 2 },
      { at: [6, 0], dir: "S", color: 3 },
    ],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 59,
    introTitle: "Grand Terminus",
    introText: "Every line in, every line out, and the timetable to keep.",
    solution: {
      paths: [
        [
          [0, 1],
          [1, 1],
          [1, 0],
          [2, 0],
          [3, 0],
          [3, 1],
          [4, 1],
          [5, 1],
          [6, 1],
          [7, 1],
          [7, 2],
          [7, 3],
          [7, 4],
          [7, 5],
          [6, 5],
          [6, 6],
          [6, 7],
        ],
        [
          [2, 7],
          [2, 6],
          [2, 5],
          [3, 5],
          [4, 5],
          [5, 5],
          [6, 5],
          [7, 5],
          [7, 4],
          [7, 3],
          [7, 2],
          [7, 1],
          [6, 1],
          [5, 1],
          [4, 1],
          [4, 0],
        ],
        [[8, 1], [7, 1], [7, 2], [7, 3], [7, 4], [7, 5], [6, 5], [6, 6], [5, 6], [4, 6], [4, 7]],
        [
          [0, 6],
          [1, 6],
          [1, 5],
          [2, 5],
          [3, 5],
          [4, 5],
          [5, 5],
          [6, 5],
          [7, 5],
          [7, 4],
          [7, 3],
          [7, 2],
          [7, 1],
          [6, 1],
          [6, 0],
        ],
      ],
      stops: [[5, 5]],
      facing: [[5, 5, "E"]],
      lamps: [[6, 1, 1], [6, 6, 0]],
      levers: [[4, 1, "N"], [6, 1, "W"], [7, 1, "W"], [6, 5, "S"], [6, 6, "S"]],
      stems: [[4, 1, "E"], [6, 1, "E"], [7, 1, "S"], [6, 5, "E"], [6, 6, "N"], [2, 5, "E"]],
    },
  },
];
