// Line 12, Night Mail. Block signals with a timetable, generated with tools/lab/blockgen.ts
// (plan in tools/lab/blockplan.ts) and picked by hand.

import type { Stop } from "../levels";

export const NIGHT_MAIL: Stop[] = [
  {
    id: "12-1",
    name: "Sorting Van",
    rows: ["TTTT.TTTTTTT", "T.TT.TTTTT.T", "T..........T", "T.TTTT...T.T", "TTTTTTTT.TTT"],
    depots: [
      { at: [0, 1], dir: "E", trains: [0, 0, 0], start: 0, every: 3 },
      { at: [11, 3], dir: "W", trains: [1, 1], start: 3, every: 4 },
      { at: [8, 4], dir: "N", trains: [2], start: 3, every: 4 },
    ],
    stations: [{ at: [11, 1], dir: "W", color: 0 }, { at: [0, 3], dir: "E", color: 1 }, { at: [4, 0], dir: "S", color: 2 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 40,
    solution: {
      paths: [
        [
          [0, 1],
          [1, 1],
          [1, 2],
          [2, 2],
          [3, 2],
          [4, 2],
          [5, 2],
          [6, 2],
          [7, 2],
          [8, 2],
          [9, 2],
          [10, 2],
          [10, 1],
          [11, 1],
        ],
        [
          [11, 3],
          [10, 3],
          [10, 2],
          [9, 2],
          [8, 2],
          [8, 3],
          [7, 3],
          [6, 3],
          [6, 2],
          [5, 2],
          [4, 2],
          [3, 2],
          [2, 2],
          [1, 2],
          [1, 3],
          [0, 3],
        ],
        [[8, 4], [8, 3], [7, 3], [6, 3], [6, 2], [5, 2], [4, 2], [4, 1], [4, 0]],
      ],
      stops: [[7, 2], [7, 3], [10, 3]],
      facing: [[7, 2, "W"], [10, 3, "N"]],
      lamps: [[4, 2, 1]],
      levers: [[1, 2, "S"], [4, 2, "W"], [6, 2, "E"], [8, 2, "S"], [10, 2, "N"]],
      stems: [[1, 2, "E"], [4, 2, "E"], [6, 2, "W"], [8, 2, "E"], [10, 2, "W"], [8, 3, "W"]],
    },
  },
  {
    id: "12-2",
    name: "Mail Bag",
    rows: [".........", "...T.....", ".........", "TTTTT.TTT", "TTTTT.TTT", ".........", ".........", "........."],
    depots: [
      { at: [0, 1], dir: "E", trains: [0, 0, 0], start: 0, every: 4 },
      { at: [0, 6], dir: "E", trains: [1, 1], start: 4, every: 4 },
      { at: [6, 0], dir: "S", trains: [2], start: 4, every: 4 },
    ],
    stations: [{ at: [8, 6], dir: "W", color: 0 }, { at: [8, 2], dir: "W", color: 1 }, { at: [2, 7], dir: "N", color: 2 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 39,
    solution: {
      paths: [
        [
          [0, 1],
          [1, 1],
          [1, 0],
          [2, 0],
          [3, 0],
          [4, 0],
          [5, 0],
          [5, 1],
          [5, 2],
          [5, 3],
          [5, 4],
          [5, 5],
          [5, 6],
          [6, 6],
          [7, 6],
          [8, 6],
        ],
        [[0, 6], [1, 6], [1, 5], [2, 5], [3, 5], [4, 5], [5, 5], [5, 4], [5, 3], [5, 2], [6, 2], [7, 2], [8, 2]],
        [
          [6, 0],
          [6, 1],
          [7, 1],
          [7, 2],
          [6, 2],
          [5, 2],
          [5, 3],
          [5, 4],
          [5, 5],
          [5, 6],
          [4, 6],
          [3, 6],
          [2, 6],
          [2, 7],
        ],
      ],
      stops: [[4, 5]],
      facing: [[4, 5, "E"]],
      lamps: [[5, 6, 0]],
      levers: [[5, 2, "E"], [5, 5, "S"], [5, 6, "E"], [7, 2, "E"]],
      stems: [[5, 2, "S"], [5, 5, "N"], [5, 6, "N"], [7, 2, "W"]],
    },
  },
  {
    id: "12-3",
    name: "Lamplighter",
    rows: ["TTTTTTTTTTTTT", "T.TTTTTTTTT.T", "T...........T", "T.TT...TTTT.T", "TTTTTTTTTTTTT"],
    depots: [
      { at: [0, 1], dir: "E", trains: [0, 0, 0], start: 0, every: 4 },
      { at: [12, 3], dir: "W", trains: [1, 1, 1], start: 1, every: 3 },
    ],
    stations: [{ at: [12, 1], dir: "W", color: 0 }, { at: [0, 3], dir: "E", color: 1 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 44,
    solution: {
      paths: [
        [
          [0, 1],
          [1, 1],
          [1, 2],
          [2, 2],
          [3, 2],
          [4, 2],
          [5, 2],
          [6, 2],
          [7, 2],
          [8, 2],
          [9, 2],
          [10, 2],
          [11, 2],
          [11, 1],
          [12, 1],
        ],
        [
          [12, 3],
          [11, 3],
          [11, 2],
          [10, 2],
          [9, 2],
          [8, 2],
          [7, 2],
          [6, 2],
          [6, 3],
          [5, 3],
          [4, 3],
          [4, 2],
          [3, 2],
          [2, 2],
          [1, 2],
          [1, 3],
          [0, 3],
        ],
      ],
      stops: [[5, 2], [4, 3], [6, 3]],
      facing: [[4, 3, "N"], [6, 3, "N"]],
      levers: [[1, 2, "S"], [4, 2, "E"], [6, 2, "S"], [11, 2, "N"]],
      stems: [[1, 2, "E"], [4, 2, "W"], [6, 2, "E"], [11, 2, "W"]],
    },
  },
  {
    id: "12-4",
    name: "Night Ferry",
    rows: [".........", "...~.~...", ".........", "~~.~~~~~~", "~~.~~~~~~", ".........", "...~.....", "........."],
    depots: [
      { at: [8, 1], dir: "W", trains: [0, 0], start: 0, every: 4 },
      { at: [7, 7], dir: "N", trains: [1, 1, 1], start: 4, every: 4 },
      { at: [0, 2], dir: "E", trains: [2, 2], start: 4, every: 5 },
    ],
    stations: [{ at: [0, 6], dir: "E", color: 0 }, { at: [6, 0], dir: "S", color: 1 }, { at: [4, 7], dir: "N", color: 2 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 50,
    solution: {
      paths: [
        [
          [8, 1],
          [7, 1],
          [7, 2],
          [6, 2],
          [5, 2],
          [4, 2],
          [3, 2],
          [2, 2],
          [2, 3],
          [2, 4],
          [2, 5],
          [2, 6],
          [1, 6],
          [0, 6],
        ],
        [
          [7, 7],
          [7, 6],
          [7, 5],
          [6, 5],
          [6, 6],
          [6, 7],
          [5, 7],
          [5, 6],
          [4, 6],
          [4, 5],
          [3, 5],
          [2, 5],
          [2, 4],
          [2, 3],
          [2, 2],
          [3, 2],
          [4, 2],
          [5, 2],
          [6, 2],
          [6, 1],
          [6, 0],
        ],
        [[0, 2], [1, 2], [2, 2], [2, 3], [2, 4], [2, 5], [3, 5], [4, 5], [4, 6], [4, 7]],
      ],
      stops: [[1, 2]],
      facing: [[1, 2, "E"]],
      lamps: [[2, 5, 0]],
      levers: [[6, 2, "N"], [2, 2, "E"], [2, 5, "S"], [4, 6, "S"]],
      stems: [[6, 2, "W"], [2, 2, "S"], [2, 5, "N"], [4, 6, "N"]],
    },
  },
  {
    id: "12-5",
    name: "Owl Express",
    rows: ["TTTTTTTT.TTTT", "T.T..TTT.TT.T", "T...........T", "T.TTTTT.TTT.T", "TTTTTTT.TTTTT"],
    depots: [
      { at: [0, 1], dir: "E", trains: [0, 0, 0], start: 0, every: 4 },
      { at: [12, 3], dir: "W", trains: [1, 1], start: 2, every: 4 },
      { at: [8, 0], dir: "S", trains: [2, 2], start: 3, every: 3 },
    ],
    stations: [{ at: [12, 1], dir: "W", color: 0 }, { at: [0, 3], dir: "E", color: 1 }, { at: [7, 4], dir: "N", color: 2 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 52,
    solution: {
      paths: [
        [
          [0, 1],
          [1, 1],
          [1, 2],
          [2, 2],
          [3, 2],
          [3, 1],
          [4, 1],
          [4, 2],
          [5, 2],
          [6, 2],
          [7, 2],
          [8, 2],
          [9, 2],
          [10, 2],
          [11, 2],
          [11, 1],
          [12, 1],
        ],
        [
          [12, 3],
          [11, 3],
          [11, 2],
          [10, 2],
          [9, 2],
          [8, 2],
          [7, 2],
          [6, 2],
          [5, 2],
          [4, 2],
          [3, 2],
          [2, 2],
          [1, 2],
          [1, 3],
          [0, 3],
        ],
        [[8, 0], [8, 1], [8, 2], [7, 2], [7, 3], [7, 4]],
      ],
      stops: [[11, 3]],
      facing: [[11, 3, "N"]],
      lamps: [[7, 2, 1]],
      levers: [[1, 2, "S"], [3, 2, "N"], [4, 2, "W"], [7, 2, "W"], [8, 2, "E"], [11, 2, "N"]],
      stems: [[1, 2, "E"], [3, 2, "W"], [4, 2, "E"], [7, 2, "E"], [8, 2, "W"], [11, 2, "W"]],
    },
  },
  {
    id: "12-6",
    name: "Postal Order",
    rows: [".........", "....T....", ".........", "T.TTTTTTT", "T.TTTTTTT", "T.TTTTTTT", ".........", "........."],
    depots: [
      { at: [0, 2], dir: "E", trains: [0, 0, 0], start: 0, every: 5 },
      { at: [0, 7], dir: "E", trains: [1, 1], start: 2, every: 5 },
      { at: [6, 0], dir: "S", trains: [3, 3], start: 4, every: 5 },
    ],
    stations: [{ at: [7, 7], dir: "N", color: 0 }, { at: [1, 0], dir: "S", color: 1 }, { at: [4, 7], dir: "N", color: 3 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 44,
    solution: {
      paths: [
        [[0, 2], [1, 2], [1, 3], [1, 4], [1, 5], [1, 6], [2, 6], [3, 6], [4, 6], [5, 6], [6, 6], [7, 6], [7, 7]],
        [[0, 7], [1, 7], [1, 6], [1, 5], [1, 4], [1, 3], [1, 2], [1, 1], [1, 0]],
        [
          [6, 0],
          [6, 1],
          [7, 1],
          [7, 2],
          [6, 2],
          [5, 2],
          [4, 2],
          [3, 2],
          [3, 1],
          [2, 1],
          [1, 1],
          [1, 2],
          [1, 3],
          [1, 4],
          [1, 5],
          [1, 6],
          [2, 6],
          [3, 6],
          [4, 6],
          [4, 7],
        ],
      ],
      stops: [[1, 7]],
      facing: [[1, 7, "N"]],
      lamps: [[4, 6, 0]],
      levers: [[1, 2, "N"], [1, 6, "E"], [4, 6, "E"], [1, 1, "N"]],
      stems: [[1, 2, "S"], [1, 6, "N"], [4, 6, "W"], [1, 1, "S"]],
    },
  },
  {
    id: "12-7",
    name: "Milk Train",
    rows: ["TTT.TTTTTTTTT", "T.T...TTTTT.T", "T...........T", "T.TTTTTT.TT.T", "TTTTTTTT.TTTT"],
    depots: [
      { at: [0, 1], dir: "E", trains: [0, 0], start: 0, every: 3, goods: true },
      { at: [12, 3], dir: "W", trains: [1, 1, 1], start: 3, every: 3 },
      { at: [3, 0], dir: "S", trains: [2], start: 2, every: 4 },
    ],
    stations: [{ at: [12, 1], dir: "W", color: 0 }, { at: [0, 3], dir: "E", color: 1 }, { at: [8, 4], dir: "N", color: 2 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 60,
    solution: {
      paths: [
        [
          [0, 1],
          [1, 1],
          [1, 2],
          [2, 2],
          [3, 2],
          [3, 1],
          [4, 1],
          [5, 1],
          [5, 2],
          [6, 2],
          [7, 2],
          [8, 2],
          [9, 2],
          [10, 2],
          [11, 2],
          [11, 1],
          [12, 1],
        ],
        [
          [12, 3],
          [11, 3],
          [11, 2],
          [10, 2],
          [9, 2],
          [8, 2],
          [7, 2],
          [6, 2],
          [5, 2],
          [4, 2],
          [3, 2],
          [2, 2],
          [1, 2],
          [1, 3],
          [0, 3],
        ],
        [[3, 0], [3, 1], [4, 1], [5, 1], [5, 2], [6, 2], [7, 2], [8, 2], [8, 3], [8, 4]],
      ],
      stops: [[5, 1], [4, 2]],
      facing: [[5, 1, "S"], [4, 2, "E"]],
      lamps: [[8, 2, 0]],
      levers: [[1, 2, "S"], [3, 2, "N"], [5, 2, "W"], [8, 2, "E"], [11, 2, "N"]],
      stems: [[1, 2, "E"], [3, 2, "W"], [3, 1, "E"], [5, 2, "E"], [8, 2, "W"], [11, 2, "W"]],
    },
  },
  {
    id: "12-8",
    name: "Night Rush",
    rows: ["TTTTTTTTT.TTT", "T.TTTTTTT.T.T", "T...........T", "T.T...TT..T.T", "TTTT.TTTTTTTT"],
    depots: [
      { at: [0, 1], dir: "E", trains: [0, 0, 0], start: 0, every: 3 },
      { at: [12, 3], dir: "W", trains: [1, 1, 1], start: 3, every: 3 },
      { at: [9, 0], dir: "S", trains: [2], start: 3, every: 4 },
    ],
    stations: [{ at: [12, 1], dir: "W", color: 0 }, { at: [0, 3], dir: "E", color: 1 }, { at: [4, 4], dir: "N", color: 2 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 47,
    introTitle: "Night rush",
    introText: "The last mail of the night, and everyone else too.",
    solution: {
      paths: [
        [
          [0, 1],
          [1, 1],
          [1, 2],
          [2, 2],
          [3, 2],
          [4, 2],
          [5, 2],
          [6, 2],
          [7, 2],
          [8, 2],
          [9, 2],
          [10, 2],
          [11, 2],
          [11, 1],
          [12, 1],
        ],
        [
          [12, 3],
          [11, 3],
          [11, 2],
          [10, 2],
          [9, 2],
          [8, 2],
          [7, 2],
          [6, 2],
          [5, 2],
          [5, 3],
          [4, 3],
          [3, 3],
          [3, 2],
          [2, 2],
          [1, 2],
          [1, 3],
          [0, 3],
        ],
        [[9, 0], [9, 1], [9, 2], [8, 2], [7, 2], [6, 2], [5, 2], [5, 3], [4, 3], [4, 4]],
      ],
      stops: [[4, 2], [3, 3], [5, 3]],
      facing: [[3, 3, "N"], [5, 3, "N"]],
      lamps: [[4, 3, 1]],
      levers: [[1, 2, "S"], [3, 2, "E"], [5, 2, "S"], [9, 2, "E"], [11, 2, "N"], [4, 3, "W"]],
      stems: [[1, 2, "E"], [3, 2, "W"], [5, 2, "E"], [9, 2, "W"], [11, 2, "W"], [4, 3, "E"]],
    },
  },
];
