// Line 4, Market Line. Block signals with a timetable, generated with tools/lab/blockgen.ts
// (plan in tools/lab/blockplan.ts) and picked by hand.

import type { Stop } from "../levels";

export const MARKET_LINE: Stop[] = [
  {
    id: "4-1",
    name: "Three Ways",
    rows: ["........", "........", "HHH.HHHH", "HHH.HHHH", "HHH.HHHH", "........", "........"],
    depots: [
      { at: [7, 1], dir: "W", trains: [0], start: 0, every: 5 },
      { at: [7, 6], dir: "W", trains: [1], start: 1, every: 5 },
      { at: [1, 0], dir: "S", trains: [2], start: 2, every: 3 },
    ],
    stations: [{ at: [0, 6], dir: "E", color: 0 }, { at: [5, 0], dir: "S", color: 1 }, { at: [4, 6], dir: "N", color: 2 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 25,
    introTitle: "One way through",
    introText: "The town has one street through it. Every line has to cross it, some each way.",
    solution: {
      paths: [
        [
          [7, 1],
          [6, 1],
          [5, 1],
          [4, 1],
          [3, 1],
          [3, 2],
          [3, 3],
          [3, 4],
          [3, 5],
          [3, 6],
          [2, 6],
          [2, 5],
          [1, 5],
          [1, 6],
          [0, 6],
        ],
        [[7, 6], [6, 6], [6, 5], [5, 5], [4, 5], [3, 5], [3, 4], [3, 3], [3, 2], [3, 1], [4, 1], [5, 1], [5, 0]],
        [[1, 0], [1, 1], [2, 1], [3, 1], [3, 2], [3, 3], [3, 4], [3, 5], [4, 5], [4, 6]],
      ],
      stops: [[5, 5]],
      facing: [[5, 5, "W"]],
      lamps: [[3, 5, 0]],
      levers: [[5, 1, "N"], [3, 1, "E"], [3, 5, "S"], [4, 5, "S"]],
      stems: [[5, 1, "W"], [3, 1, "S"], [3, 5, "N"], [4, 5, "W"]],
    },
  },
  {
    id: "4-2",
    name: "Stallholders",
    rows: [".......", "....H..", "H.HHHHH", "H.HHHHH", ".......", "....H..", "......."],
    depots: [
      { at: [6, 1], dir: "W", trains: [0, 0], start: 0, every: 3 },
      { at: [1, 6], dir: "N", trains: [1], start: 3, every: 3 },
      { at: [2, 0], dir: "S", trains: [2], start: 2, every: 5 },
    ],
    stations: [{ at: [3, 6], dir: "N", color: 0 }, { at: [0, 1], dir: "E", color: 1 }, { at: [6, 5], dir: "W", color: 2 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 24,
    solution: {
      paths: [
        [
          [6, 1],
          [5, 1],
          [5, 0],
          [4, 0],
          [3, 0],
          [3, 1],
          [2, 1],
          [1, 1],
          [1, 2],
          [1, 3],
          [1, 4],
          [2, 4],
          [3, 4],
          [3, 5],
          [3, 6],
        ],
        [[1, 6], [1, 5], [1, 4], [1, 3], [1, 2], [1, 1], [0, 1]],
        [[2, 0], [2, 1], [1, 1], [1, 2], [1, 3], [1, 4], [2, 4], [3, 4], [4, 4], [5, 4], [5, 5], [6, 5]],
      ],
      stops: [[1, 5]],
      facing: [[1, 5, "N"]],
      lamps: [[3, 4, 0]],
      levers: [[1, 1, "W"], [1, 4, "E"], [3, 4, "S"]],
      stems: [[2, 1, "W"], [1, 1, "S"], [1, 4, "N"], [3, 4, "W"]],
    },
  },
  {
    id: "4-3",
    name: "Corn Exchange",
    rows: ["........", "........", "HHH.HHHH", "HHH.HHHH", "........", ".H.H....", "........"],
    depots: [
      { at: [4, 0], dir: "S", trains: [0, 0], start: 0, every: 4 },
      { at: [4, 6], dir: "N", trains: [1, 1], start: 3, every: 3 },
      { at: [7, 1], dir: "W", trains: [2], start: 4, every: 3 },
    ],
    stations: [{ at: [7, 5], dir: "W", color: 0 }, { at: [0, 1], dir: "E", color: 1 }, { at: [2, 6], dir: "N", color: 2 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 32,
    solution: {
      paths: [
        [[4, 0], [4, 1], [3, 1], [3, 2], [3, 3], [3, 4], [4, 4], [5, 4], [6, 4], [6, 5], [7, 5]],
        [[4, 6], [4, 5], [4, 4], [3, 4], [3, 3], [3, 2], [3, 1], [2, 1], [1, 1], [0, 1]],
        [[7, 1], [6, 1], [5, 1], [4, 1], [3, 1], [3, 2], [3, 3], [3, 4], [2, 4], [2, 5], [2, 6]],
      ],
      stops: [[4, 5]],
      facing: [[4, 5, "N"]],
      lamps: [[3, 4, 0]],
      levers: [[3, 1, "W"], [3, 4, "E"], [4, 4, "E"]],
      stems: [[4, 1, "W"], [3, 1, "S"], [3, 4, "N"], [4, 4, "W"]],
    },
  },
  {
    id: "4-4",
    name: "Market Cross",
    rows: ["........", "...H....", "........", "HHHHH.HH", "HHHHH.HH", "HHHHH.HH", "........", "........"],
    depots: [
      { at: [7, 2], dir: "W", trains: [0], start: 0, every: 4 },
      { at: [7, 7], dir: "W", trains: [1, 1], start: 4, every: 3 },
      { at: [0, 2], dir: "E", trains: [2, 2], start: 4, every: 5 },
    ],
    stations: [{ at: [0, 7], dir: "E", color: 0 }, { at: [5, 0], dir: "S", color: 1 }, { at: [4, 7], dir: "N", color: 2 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 38,
    solution: {
      paths: [
        [
          [7, 2],
          [6, 2],
          [6, 1],
          [5, 1],
          [5, 2],
          [5, 3],
          [5, 4],
          [5, 5],
          [5, 6],
          [4, 6],
          [3, 6],
          [3, 7],
          [2, 7],
          [1, 7],
          [0, 7],
        ],
        [[7, 7], [6, 7], [6, 6], [5, 6], [5, 5], [5, 4], [5, 3], [5, 2], [5, 1], [5, 0]],
        [
          [0, 2],
          [1, 2],
          [1, 1],
          [2, 1],
          [2, 2],
          [3, 2],
          [4, 2],
          [5, 2],
          [5, 3],
          [5, 4],
          [5, 5],
          [5, 6],
          [4, 6],
          [4, 7],
        ],
      ],
      stops: [[6, 6]],
      facing: [[6, 6, "W"]],
      lamps: [[4, 6, 0]],
      levers: [[5, 1, "N"], [5, 2, "N"], [5, 6, "W"], [4, 6, "W"]],
      stems: [[5, 1, "S"], [5, 2, "S"], [5, 6, "N"], [4, 6, "E"]],
    },
  },
  {
    id: "4-5",
    name: "Weighbridge",
    rows: ["........", "...H....", "........", "HHHHH.HH", "HHHHH.HH", "HHHHH.HH", "........", "........"],
    depots: [
      { at: [7, 2], dir: "W", trains: [0, 0], start: 0, every: 4 },
      { at: [7, 7], dir: "W", trains: [1, 1], start: 4, every: 3 },
      { at: [0, 2], dir: "E", trains: [2], start: 4, every: 5 },
    ],
    stations: [{ at: [0, 7], dir: "E", color: 0 }, { at: [5, 0], dir: "S", color: 1 }, { at: [4, 7], dir: "N", color: 2 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 34,
    solution: {
      paths: [
        [
          [7, 2],
          [6, 2],
          [6, 1],
          [5, 1],
          [5, 2],
          [5, 3],
          [5, 4],
          [5, 5],
          [5, 6],
          [4, 6],
          [3, 6],
          [3, 7],
          [2, 7],
          [1, 7],
          [0, 7],
        ],
        [[7, 7], [6, 7], [6, 6], [5, 6], [5, 5], [5, 4], [5, 3], [5, 2], [5, 1], [5, 0]],
        [
          [0, 2],
          [1, 2],
          [1, 1],
          [2, 1],
          [2, 2],
          [3, 2],
          [4, 2],
          [5, 2],
          [5, 3],
          [5, 4],
          [5, 5],
          [5, 6],
          [4, 6],
          [4, 7],
        ],
      ],
      stops: [[6, 6]],
      facing: [[6, 6, "W"]],
      lamps: [[4, 6, 0]],
      levers: [[5, 1, "N"], [5, 2, "N"], [5, 6, "W"], [4, 6, "W"]],
      stems: [[5, 1, "S"], [5, 2, "S"], [5, 6, "N"], [4, 6, "E"]],
    },
  },
  {
    id: "4-6",
    name: "Haberdashers",
    rows: [".........", ".....H...", ".........", "HH.HHH.HH", "HH.HHH.HH", "HH.HHH.HH", ".........", "........."],
    depots: [
      { at: [6, 0], dir: "S", trains: [0, 0], start: 0, every: 5 },
      { at: [0, 7], dir: "E", trains: [1, 1], start: 4, every: 3 },
      { at: [3, 0], dir: "S", trains: [2], start: 3, every: 5 },
    ],
    stations: [{ at: [2, 7], dir: "N", color: 0 }, { at: [0, 1], dir: "E", color: 1 }, { at: [8, 7], dir: "W", color: 2 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 31,
    introTitle: "Two streets",
    introText: "Two ways through town now. Which line takes which?",
    solution: {
      paths: [
        [
          [6, 0],
          [6, 1],
          [7, 1],
          [8, 1],
          [8, 2],
          [7, 2],
          [6, 2],
          [5, 2],
          [4, 2],
          [3, 2],
          [2, 2],
          [2, 3],
          [2, 4],
          [2, 5],
          [2, 6],
          [2, 7],
        ],
        [[0, 7], [1, 7], [1, 6], [2, 6], [2, 5], [2, 4], [2, 3], [2, 2], [2, 1], [1, 1], [0, 1]],
        [[3, 0], [3, 1], [4, 1], [4, 2], [5, 2], [6, 2], [6, 3], [6, 4], [6, 5], [6, 6], [7, 6], [7, 7], [8, 7]],
      ],
      stops: [[3, 1], [3, 2]],
      facing: [[3, 1, "E"]],
      levers: [[6, 2, "S"], [4, 2, "W"], [2, 2, "N"], [2, 6, "S"]],
      stems: [[6, 2, "W"], [4, 2, "E"], [2, 2, "S"], [2, 6, "N"]],
    },
  },
  {
    id: "4-7",
    name: "Clock Tower",
    rows: [".........", ".......H.", ".........", "HH.HHH.HH", "HH.HHH.HH", ".........", ".........", "........."],
    depots: [
      { at: [4, 0], dir: "S", trains: [0, 0], start: 0, every: 3 },
      { at: [4, 7], dir: "N", trains: [1, 1], start: 4, every: 4 },
      { at: [2, 0], dir: "S", trains: [2], start: 4, every: 4 },
    ],
    stations: [{ at: [8, 6], dir: "W", color: 0 }, { at: [8, 2], dir: "W", color: 1 }, { at: [6, 7], dir: "N", color: 2 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 29,
    solution: {
      paths: [
        [[4, 0], [4, 1], [5, 1], [6, 1], [6, 2], [6, 3], [6, 4], [6, 5], [6, 6], [7, 6], [8, 6]],
        [[4, 7], [4, 6], [4, 5], [5, 5], [6, 5], [6, 4], [6, 3], [6, 2], [7, 2], [8, 2]],
        [[2, 0], [2, 1], [3, 1], [4, 1], [5, 1], [6, 1], [6, 2], [6, 3], [6, 4], [6, 5], [6, 6], [6, 7]],
      ],
      stops: [[5, 5]],
      facing: [[5, 5, "E"]],
      lamps: [[6, 6, 0]],
      levers: [[6, 2, "E"], [6, 5, "S"], [6, 6, "E"]],
      stems: [[4, 1, "E"], [6, 2, "S"], [6, 5, "N"], [6, 6, "N"]],
    },
  },
  {
    id: "4-8",
    name: "Market Day",
    rows: [".........", "..H......", ".........", "HH.HHHHHH", "HH.HHHHHH", ".........", ".........", "........."],
    depots: [
      { at: [0, 2], dir: "E", trains: [0, 0], start: 0, every: 4 },
      { at: [8, 6], dir: "W", trains: [1, 1], start: 2, every: 4 },
      { at: [1, 0], dir: "S", trains: [2, 2], start: 3, every: 4 },
    ],
    stations: [{ at: [6, 7], dir: "N", color: 0 }, { at: [8, 1], dir: "W", color: 1 }, { at: [0, 6], dir: "E", color: 2 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 45,
    introTitle: "Market day",
    introText: "Everyone wants the one street at once.",
    solution: {
      paths: [
        [[0, 2], [1, 2], [2, 2], [2, 3], [2, 4], [2, 5], [3, 5], [4, 5], [5, 5], [6, 5], [6, 6], [6, 7]],
        [
          [8, 6],
          [7, 6],
          [7, 5],
          [6, 5],
          [6, 6],
          [5, 6],
          [5, 5],
          [4, 5],
          [4, 6],
          [3, 6],
          [2, 6],
          [2, 5],
          [2, 4],
          [2, 3],
          [2, 2],
          [3, 2],
          [3, 1],
          [4, 1],
          [5, 1],
          [6, 1],
          [7, 1],
          [8, 1],
        ],
        [[1, 0], [1, 1], [1, 2], [2, 2], [2, 3], [2, 4], [2, 5], [2, 6], [1, 6], [0, 6]],
      ],
      stops: [[1, 1], [3, 5], [4, 6]],
      facing: [[1, 1, "S"], [3, 5, "E"], [4, 6, "N"]],
      lamps: [[2, 5, 0], [6, 6, 0]],
      levers: [[2, 2, "E"], [2, 5, "E"], [4, 5, "S"], [5, 5, "E"], [6, 6, "S"], [2, 6, "W"]],
      stems: [[1, 2, "E"], [2, 2, "S"], [2, 5, "N"], [4, 5, "E"], [5, 5, "W"], [6, 5, "S"], [6, 6, "N"], [2, 6, "N"]],
    },
  },
];
