// Line 9, Festival Line. Generated with tools/campaign and curated by hand.

import type { Stop } from "../levels";

export const FESTIVAL_LINE: Stop[] = [
  {
    id: "9-1",
    name: "Bunting",
    rows: [".......", "T......", ".......", ".......", ".......", ".TTTT..", ".......", "..~...."],
    depots: [
      { at: [3, 0], dir: "S", trains: [3, 0], every: 4, start: 0 },
      { at: [4, 7], dir: "N", trains: [0], every: 3, start: 2 },
    ],
    stations: [{ at: [6, 1], dir: "W", color: 0 }, { at: [6, 3], dir: "W", color: 3 }],
    allowStop: true,
    allowLamp: true,
    introTitle: "Fourth colour",
    introText: "Tangerine trains, with a diamond, join the timetable.",
    solution: {
      paths: [
        [[3, 0], [3, 1], [4, 1], [4, 0], [5, 0], [5, 1], [6, 1]],
        [[3, 0], [3, 1], [4, 1], [4, 2], [4, 3], [5, 3], [6, 3]],
        [[4, 7], [4, 6], [5, 6], [5, 5], [5, 4], [5, 3], [5, 2], [5, 1], [6, 1]],
      ],
      stops: [[4, 6]],
      lamps: [[4, 1, 0]],
      levers: [[4, 1, "N"]],
    },
  },
  {
    id: "9-2",
    name: "Bandstand",
    rows: ["...T....", "........", "........", "........", "........", "........", "..HH....", "...H...."],
    depots: [
      { at: [7, 4], dir: "W", trains: [3, 0, 3], every: 3, start: 2 },
      { at: [0, 3], dir: "E", trains: [1], every: 3, start: 0 },
    ],
    stations: [{ at: [4, 0], dir: "S", color: 0 }, { at: [4, 7], dir: "N", color: 1 }, { at: [0, 6], dir: "E", color: 3 }],
    allowStop: true,
    allowLamp: true,
    solution: {
      paths: [
        [[0, 3], [1, 3], [1, 4], [1, 5], [2, 5], [3, 5], [4, 5], [4, 6], [4, 7]],
        [[7, 4], [6, 4], [5, 4], [4, 4], [4, 5], [3, 5], [2, 5], [1, 5], [1, 6], [0, 6]],
        [[7, 4], [6, 4], [5, 4], [4, 4], [4, 3], [4, 2], [4, 1], [4, 0]],
      ],
      stops: [[6, 4]],
      lamps: [[4, 4, 3]],
      levers: [[4, 5, "S"], [4, 4, "S"], [1, 5, "S"]],
    },
  },
  {
    id: "9-3",
    name: "Four Ways",
    rows: ["........", "........", "........", ".....T..", "....TT..", "....T...", "........", ".H......"],
    depots: [{ at: [7, 3], dir: "W", trains: [0, 1, 2, 3], every: 4, start: 1 }],
    stations: [
      { at: [7, 1], dir: "W", color: 0 },
      { at: [0, 2], dir: "E", color: 1 },
      { at: [1, 0], dir: "S", color: 2 },
      { at: [3, 7], dir: "N", color: 3 },
    ],
    allowStop: true,
    allowLamp: true,
    introTitle: "Four colours",
    introText: "Three colour signals, four platforms.",
    solution: {
      paths: [
        [[7, 3], [6, 3], [6, 4], [6, 5], [6, 6], [5, 6], [4, 6], [3, 6], [3, 7]],
        [[7, 3], [6, 3], [6, 2], [6, 1], [7, 1]],
        [[7, 3], [6, 3], [6, 2], [6, 1], [5, 1], [4, 1], [3, 1], [2, 1], [1, 1], [1, 0]],
        [[7, 3], [6, 3], [6, 2], [6, 1], [5, 1], [4, 1], [3, 1], [2, 1], [1, 1], [1, 2], [0, 2]],
      ],
      lamps: [[6, 3, 3], [6, 1, 0], [1, 1, 2]],
      levers: [[6, 3, "S"], [6, 1, "E"], [1, 1, "N"]],
    },
  },
  {
    id: "9-4",
    name: "Carousel",
    rows: ["........", "........", "....T...", "......TT", "......TT", "....T...", "........", "........"],
    depots: [
      { at: [6, 0], dir: "S", trains: [0], every: 3, start: 3 },
      { at: [2, 0], dir: "S", trains: [1], every: 3, start: 3 },
      { at: [4, 7], dir: "N", trains: [2], every: 3, start: 0 },
      { at: [2, 7], dir: "N", trains: [3], every: 3, start: 1 },
    ],
    stations: [
      { at: [7, 2], dir: "W", color: 0 },
      { at: [0, 3], dir: "E", color: 1 },
      { at: [0, 1], dir: "E", color: 2 },
      { at: [6, 7], dir: "N", color: 3 },
    ],
    allowStop: true,
    allowLamp: true,
    solution: {
      paths: [
        [[6, 0], [6, 1], [6, 2], [7, 2]],
        [[4, 7], [4, 6], [3, 6], [2, 6], [1, 6], [1, 5], [1, 4], [1, 3], [1, 2], [1, 1], [0, 1]],
        [[2, 0], [2, 1], [2, 2], [2, 3], [1, 3], [0, 3]],
        [[2, 7], [2, 6], [2, 5], [2, 4], [3, 4], [4, 4], [5, 4], [5, 5], [5, 6], [6, 6], [6, 7]],
      ],
      stops: [[3, 6]],
    },
  },
  {
    id: "9-5",
    name: "Fireworks",
    rows: ["....HH..", ".....H..", "........", "........", "........", "........", "......TT", ".......T"],
    depots: [
      { at: [0, 5], dir: "E", trains: [3, 2], every: 3, start: 1 },
      { at: [7, 1], dir: "W", trains: [1, 0], every: 3, start: 1 },
    ],
    stations: [
      { at: [7, 4], dir: "W", color: 0 },
      { at: [2, 0], dir: "S", color: 1, opens: 13 },
      { at: [0, 3], dir: "E", color: 2 },
      { at: [2, 7], dir: "N", color: 3 },
    ],
    allowStop: true,
    allowLamp: true,
    solution: {
      paths: [
        [[7, 1], [6, 1], [6, 2], [5, 2], [4, 2], [4, 1], [3, 1], [2, 1], [2, 0]],
        [[0, 5], [1, 5], [1, 6], [2, 6], [2, 7]],
        [[0, 5], [1, 5], [1, 4], [1, 3], [0, 3]],
        [[7, 1], [6, 1], [6, 2], [7, 2], [7, 3], [6, 3], [6, 4], [7, 4]],
      ],
      stops: [[4, 2], [4, 1]],
      lamps: [[6, 2, 1], [1, 5, 3]],
      levers: [[6, 2, "W"], [1, 5, "S"]],
    },
  },
  {
    id: "9-6",
    name: "Ferris Wheel",
    rows: ["..TTTT..", "..T..T..", "........", "TT.^^^^^", ".T.^^^^^", "........", "........", "........"],
    depots: [
      { at: [4, 7], dir: "N", trains: [3, 0], every: 3, start: 1 },
      { at: [1, 7], dir: "N", trains: [1], every: 3, start: 1 },
      { at: [0, 1], dir: "E", trains: [2], every: 3, start: 1 },
    ],
    stations: [
      { at: [7, 1], dir: "W", color: 0 },
      { at: [0, 5], dir: "E", color: 1 },
      { at: [7, 5], dir: "W", color: 2 },
      { at: [6, 7], dir: "N", color: 3 },
    ],
    tunnels: [[[5, 3], [5, 4]]],
    allowStop: true,
    allowLamp: true,
    solution: {
      paths: [
        [[1, 7], [1, 6], [1, 5], [0, 5]],
        [[4, 7], [4, 6], [3, 6], [3, 5], [4, 5], [5, 5], [5, 4], [5, 3], [5, 2], [6, 2], [6, 1], [7, 1]],
        [[0, 1], [1, 1], [1, 2], [2, 2], [3, 2], [4, 2], [5, 2], [5, 3], [5, 4], [5, 5], [6, 5], [7, 5]],
        [[4, 7], [4, 6], [5, 6], [6, 6], [6, 7]],
      ],
      stops: [[3, 6]],
      lamps: [[4, 6, 0]],
      levers: [[4, 6, "W"], [5, 2, "E"], [5, 5, "E"]],
    },
  },
  {
    id: "9-7",
    name: "Last Orders",
    rows: ["........", "........", "........", "........", "........", "..T~~...", "........", "........", "........"],
    depots: [
      { at: [1, 0], dir: "S", trains: [3], every: 3, start: 3, goods: true },
      { at: [6, 8], dir: "N", trains: [0, 1, 0], every: 4, start: 1 },
      { at: [6, 0], dir: "S", trains: [2], every: 3, start: 1 },
    ],
    stations: [
      { at: [4, 8], dir: "N", color: 0 },
      { at: [4, 0], dir: "S", color: 1 },
      { at: [0, 4], dir: "E", color: 2 },
      { at: [1, 8], dir: "N", color: 3 },
    ],
    allowStop: true,
    allowLamp: true,
    solution: {
      paths: [
        [[6, 0], [6, 1], [5, 1], [5, 2], [5, 3], [5, 4], [4, 4], [3, 4], [2, 4], [1, 4], [0, 4]],
        [[6, 8], [6, 7], [5, 7], [4, 7], [4, 8]],
        [[6, 8], [6, 7], [7, 7], [7, 6], [7, 5], [7, 4], [6, 4], [5, 4], [5, 3], [5, 2], [5, 1], [4, 1], [4, 0]],
        [[1, 0], [1, 1], [1, 2], [1, 3], [1, 4], [1, 5], [1, 6], [1, 7], [1, 8]],
      ],
      stops: [[1, 1]],
      lamps: [[6, 7, 0]],
      levers: [[5, 4, "W"], [6, 7, "W"], [5, 1, "W"]],
    },
  },
  {
    id: "9-8",
    name: "Festival Rush",
    rows: [".......T", ".....H..", "..T.....", "..T.....", "...H....", "..T.....", "..T.....", ".....H..", ".......T"],
    depots: [
      { at: [0, 5], dir: "E", trains: [0, 3, 1], every: 4, start: 3 },
      { at: [2, 0], dir: "S", trains: [2, 0], every: 4, start: 0 },
      { at: [1, 8], dir: "N", trains: [3, 1], every: 4, start: 3 },
    ],
    stations: [
      { at: [0, 2], dir: "E", color: 0 },
      { at: [6, 8], dir: "N", color: 1 },
      { at: [7, 3], dir: "W", color: 2 },
      { at: [7, 1], dir: "W", color: 3 },
    ],
    allowStop: true,
    allowLamp: true,
    introTitle: "Festival rush",
    introText: "Four colours, everyone heading home at once.",
    solution: {
      paths: [
        [[0, 5], [1, 5], [1, 6], [1, 7], [2, 7], [3, 7], [3, 6], [4, 6], [5, 6], [6, 6], [6, 7], [6, 8]],
        [[2, 0], [2, 1], [1, 1], [1, 2], [0, 2]],
        [
          [0, 5],
          [1, 5],
          [1, 6],
          [1, 7],
          [2, 7],
          [3, 7],
          [3, 6],
          [4, 6],
          [5, 6],
          [6, 6],
          [6, 5],
          [6, 4],
          [6, 3],
          [6, 2],
          [6, 1],
          [7, 1],
        ],
        [[2, 0], [2, 1], [3, 1], [4, 1], [4, 2], [4, 3], [5, 3], [6, 3], [7, 3]],
        [
          [1, 8],
          [1, 7],
          [2, 7],
          [3, 7],
          [3, 6],
          [4, 6],
          [5, 6],
          [6, 6],
          [6, 5],
          [6, 4],
          [6, 3],
          [6, 2],
          [6, 1],
          [7, 1],
        ],
        [[0, 5], [1, 5], [1, 4], [1, 3], [1, 2], [0, 2]],
        [[1, 8], [1, 7], [2, 7], [3, 7], [3, 6], [4, 6], [5, 6], [6, 6], [6, 7], [6, 8]],
      ],
      stops: [[1, 1]],
      lamps: [[1, 5, 0], [6, 6, 1], [2, 1, 0]],
      levers: [[1, 5, "N"], [6, 6, "S"], [2, 1, "W"]],
    },
  },
];
