// Line 8, Junction Line. Block signals with a timetable, generated with tools/lab/blockgen.ts
// (plan in tools/lab/blockplan.ts) and picked by hand.

import type { Stop } from "../levels";

export const JUNCTION_LINE: Stop[] = [
  {
    id: "8-1",
    name: "Old Spur",
    rows: ["........", "........", "........", "TTTTT.TT", "TTTTT.TT", "TTTTT.TT", "........", "........"],
    depots: [
      { at: [7, 2], dir: "W", trains: [0, 1], start: 0, every: 3 },
      { at: [3, 7], dir: "N", trains: [2], start: 1, every: 4 },
    ],
    stations: [{ at: [7, 7], dir: "W", color: 0 }, { at: [0, 7], dir: "E", color: 1 }, { at: [4, 0], dir: "S", color: 2 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 31,
    introTitle: "Sort after the gap",
    introText: "Two colours share a depot. Send them through the gap together, then sort them with a colour signal.",
    solution: {
      paths: [
        [[7, 2], [6, 2], [5, 2], [5, 3], [5, 4], [5, 5], [5, 6], [6, 6], [6, 7], [7, 7]],
        [
          [7, 2],
          [6, 2],
          [6, 1],
          [5, 1],
          [5, 2],
          [5, 3],
          [5, 4],
          [5, 5],
          [5, 6],
          [4, 6],
          [3, 6],
          [2, 6],
          [2, 7],
          [1, 7],
          [0, 7],
        ],
        [[3, 7], [3, 6], [4, 6], [5, 6], [5, 5], [5, 4], [5, 3], [5, 2], [5, 1], [4, 1], [4, 0]],
      ],
      stops: [[6, 1], [4, 6]],
      facing: [[4, 6, "E"]],
      lamps: [[6, 2, 0], [5, 6, 0]],
      levers: [[6, 2, "W"], [5, 2, "N"], [5, 6, "E"], [5, 1, "W"], [3, 6, "W"]],
      stems: [[6, 2, "E"], [5, 2, "S"], [5, 6, "N"], [5, 1, "S"], [3, 6, "E"]],
    },
  },
  {
    id: "8-2",
    name: "Points Failure",
    rows: ["........", "........", "........", "TTTTTT.T", "TTTTTT.T", "........", ".T.T....", "........"],
    depots: [
      { at: [0, 1], dir: "E", trains: [0, 1], start: 0, every: 3 },
      { at: [4, 7], dir: "N", trains: [2, 2], start: 4, every: 3 },
    ],
    stations: [{ at: [7, 6], dir: "W", color: 0 }, { at: [2, 7], dir: "N", color: 1 }, { at: [4, 0], dir: "S", color: 2 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 35,
    solution: {
      paths: [
        [
          [0, 1],
          [1, 1],
          [1, 0],
          [2, 0],
          [3, 0],
          [3, 1],
          [4, 1],
          [5, 1],
          [6, 1],
          [6, 2],
          [6, 3],
          [6, 4],
          [6, 5],
          [6, 6],
          [7, 6],
        ],
        [
          [0, 1],
          [1, 1],
          [1, 0],
          [2, 0],
          [3, 0],
          [3, 1],
          [4, 1],
          [5, 1],
          [6, 1],
          [6, 2],
          [6, 3],
          [6, 4],
          [6, 5],
          [6, 6],
          [5, 6],
          [4, 6],
          [4, 5],
          [3, 5],
          [2, 5],
          [2, 6],
          [2, 7],
        ],
        [[4, 7], [4, 6], [4, 5], [5, 5], [6, 5], [6, 4], [6, 3], [6, 2], [6, 1], [5, 1], [4, 1], [4, 0]],
      ],
      stops: [[5, 5], [5, 6]],
      facing: [[5, 5, "E"], [5, 6, "E"]],
      lamps: [[6, 6, 0], [4, 5, 1]],
      levers: [[4, 1, "N"], [6, 5, "S"], [6, 6, "E"], [4, 5, "W"]],
      stems: [[4, 1, "E"], [6, 5, "N"], [6, 6, "N"], [4, 6, "N"], [4, 5, "S"]],
    },
  },
  {
    id: "8-3",
    name: "Signal Box",
    rows: ["........", "........", "........", "TTTTT.TT", "TTTTT.TT", "TTTTT.TT", "........", "........"],
    depots: [
      { at: [7, 2], dir: "W", trains: [0, 1, 0], start: 0, every: 3 },
      { at: [3, 7], dir: "N", trains: [2], start: 1, every: 4 },
    ],
    stations: [{ at: [7, 7], dir: "W", color: 0 }, { at: [0, 7], dir: "E", color: 1 }, { at: [4, 0], dir: "S", color: 2 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 37,
    solution: {
      paths: [
        [[7, 2], [6, 2], [6, 1], [5, 1], [5, 2], [5, 3], [5, 4], [5, 5], [5, 6], [6, 6], [6, 7], [7, 7]],
        [
          [7, 2],
          [6, 2],
          [6, 1],
          [5, 1],
          [5, 2],
          [5, 3],
          [5, 4],
          [5, 5],
          [5, 6],
          [4, 6],
          [3, 6],
          [2, 6],
          [2, 7],
          [1, 7],
          [0, 7],
        ],
        [[3, 7], [3, 6], [4, 6], [5, 6], [5, 5], [5, 4], [5, 3], [5, 2], [5, 1], [4, 1], [4, 0]],
      ],
      stops: [[6, 2], [4, 6]],
      facing: [[6, 2, "N"], [4, 6, "E"]],
      lamps: [[5, 6, 0]],
      levers: [[5, 1, "W"], [5, 6, "E"], [3, 6, "W"]],
      stems: [[5, 1, "S"], [5, 6, "N"], [3, 6, "E"]],
    },
  },
  {
    id: "8-4",
    name: "Engine Shed",
    rows: [".........", "...T.....", ".........", "TT.TT.TTT", "TT.TT.TTT", "TT.TT.TTT", ".........", "........."],
    depots: [
      { at: [0, 2], dir: "E", trains: [0, 1], start: 0, every: 3 },
      { at: [8, 7], dir: "W", trains: [2, 2], start: 4, every: 3 },
    ],
    stations: [{ at: [6, 7], dir: "N", color: 0 }, { at: [0, 7], dir: "E", color: 1 }, { at: [7, 0], dir: "S", color: 2 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 28,
    solution: {
      paths: [
        [
          [0, 2],
          [1, 2],
          [1, 1],
          [1, 0],
          [2, 0],
          [3, 0],
          [4, 0],
          [5, 0],
          [5, 1],
          [5, 2],
          [5, 3],
          [5, 4],
          [5, 5],
          [5, 6],
          [6, 6],
          [6, 7],
        ],
        [[0, 2], [1, 2], [2, 2], [2, 3], [2, 4], [2, 5], [2, 6], [2, 7], [1, 7], [0, 7]],
        [[8, 7], [7, 7], [7, 6], [6, 6], [5, 6], [5, 5], [5, 4], [5, 3], [5, 2], [5, 1], [6, 1], [7, 1], [7, 0]],
      ],
      stops: [[5, 0]],
      facing: [[5, 0, "S"]],
      lamps: [[1, 2, 0]],
      levers: [[1, 2, "N"], [5, 1, "E"], [6, 6, "S"]],
      stems: [[1, 2, "W"], [5, 1, "S"], [6, 6, "W"]],
    },
  },
  {
    id: "8-5",
    name: "Turntable",
    rows: [".........", ".T.T..T..", ".........", "TTTTT.TTT", "TTTTT.TTT", ".........", ".........", "........."],
    depots: [
      { at: [8, 1], dir: "W", trains: [0, 1, 0], start: 0, every: 5 },
      { at: [4, 7], dir: "N", trains: [2, 2], start: 1, every: 5 },
    ],
    stations: [{ at: [0, 6], dir: "E", color: 0 }, { at: [8, 6], dir: "W", color: 1 }, { at: [4, 0], dir: "S", color: 2 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 36,
    solution: {
      paths: [
        [
          [8, 1],
          [7, 1],
          [7, 0],
          [6, 0],
          [5, 0],
          [5, 1],
          [5, 2],
          [5, 3],
          [5, 4],
          [5, 5],
          [6, 5],
          [6, 6],
          [5, 6],
          [4, 6],
          [3, 6],
          [2, 6],
          [1, 6],
          [0, 6],
        ],
        [
          [8, 1],
          [7, 1],
          [7, 0],
          [6, 0],
          [5, 0],
          [5, 1],
          [5, 2],
          [5, 3],
          [5, 4],
          [5, 5],
          [6, 5],
          [6, 6],
          [7, 6],
          [8, 6],
        ],
        [[4, 7], [4, 6], [4, 5], [5, 5], [5, 4], [5, 3], [5, 2], [5, 1], [4, 1], [4, 0]],
      ],
      stops: [[4, 5], [6, 5]],
      facing: [[4, 5, "E"], [6, 5, "W"]],
      lamps: [[6, 6, 0]],
      levers: [[5, 1, "W"], [5, 5, "E"], [6, 6, "W"]],
      stems: [[5, 1, "S"], [5, 5, "N"], [6, 6, "N"]],
    },
  },
  {
    id: "8-6",
    name: "Goods Yard",
    rows: [".........", ".T.......", ".........", "TTT.TTTTT", "TTT.TTTTT", "TTT.TTTTT", ".........", "........."],
    depots: [
      { at: [7, 0], dir: "S", trains: [0, 1], start: 0, every: 3 },
      { at: [5, 7], dir: "N", trains: [2], start: 4, every: 4, goods: true },
    ],
    stations: [{ at: [0, 7], dir: "E", color: 0 }, { at: [8, 7], dir: "W", color: 1 }, { at: [5, 0], dir: "S", color: 2 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 44,
    solution: {
      paths: [
        [
          [7, 0],
          [7, 1],
          [8, 1],
          [8, 2],
          [7, 2],
          [6, 2],
          [6, 1],
          [5, 1],
          [5, 2],
          [4, 2],
          [3, 2],
          [3, 3],
          [3, 4],
          [3, 5],
          [3, 6],
          [3, 7],
          [2, 7],
          [1, 7],
          [0, 7],
        ],
        [
          [7, 0],
          [7, 1],
          [8, 1],
          [8, 2],
          [7, 2],
          [6, 2],
          [6, 1],
          [5, 1],
          [5, 2],
          [4, 2],
          [3, 2],
          [3, 3],
          [3, 4],
          [3, 5],
          [3, 6],
          [4, 6],
          [5, 6],
          [6, 6],
          [7, 6],
          [7, 7],
          [8, 7],
        ],
        [
          [5, 7],
          [5, 6],
          [4, 6],
          [4, 7],
          [3, 7],
          [3, 6],
          [3, 5],
          [3, 4],
          [3, 3],
          [3, 2],
          [4, 2],
          [5, 2],
          [5, 1],
          [5, 0],
        ],
      ],
      stops: [[4, 7]],
      facing: [[4, 7, "W"]],
      lamps: [[3, 6, 0]],
      levers: [[5, 1, "N"], [3, 6, "S"], [3, 7, "W"], [4, 6, "S"], [5, 6, "E"]],
      stems: [[5, 1, "S"], [3, 6, "N"], [3, 7, "N"], [4, 6, "E"], [5, 6, "W"]],
    },
  },
  {
    id: "8-7",
    name: "Diamond Crossing",
    rows: [".........", ".T.T..T..", ".........", "TTTTT.TTT", "TTTTT.TTT", ".........", ".........", "........."],
    depots: [
      { at: [8, 1], dir: "W", trains: [0, 1], start: 0, every: 5 },
      { at: [4, 7], dir: "N", trains: [2, 2], start: 1, every: 5 },
      { at: [0, 2], dir: "E", trains: [0], start: 2, every: 4 },
    ],
    stations: [{ at: [0, 6], dir: "E", color: 0 }, { at: [8, 6], dir: "W", color: 1 }, { at: [4, 0], dir: "S", color: 2 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 34,
    solution: {
      paths: [
        [
          [8, 1],
          [7, 1],
          [7, 0],
          [6, 0],
          [5, 0],
          [5, 1],
          [5, 2],
          [5, 3],
          [5, 4],
          [5, 5],
          [6, 5],
          [6, 6],
          [5, 6],
          [4, 6],
          [3, 6],
          [2, 6],
          [1, 6],
          [0, 6],
        ],
        [
          [8, 1],
          [7, 1],
          [7, 0],
          [6, 0],
          [5, 0],
          [5, 1],
          [5, 2],
          [5, 3],
          [5, 4],
          [5, 5],
          [6, 5],
          [7, 5],
          [7, 6],
          [8, 6],
        ],
        [[4, 7], [4, 6], [4, 5], [5, 5], [5, 4], [5, 3], [5, 2], [5, 1], [4, 1], [4, 0]],
        [
          [0, 2],
          [1, 2],
          [2, 2],
          [3, 2],
          [4, 2],
          [4, 1],
          [5, 1],
          [5, 2],
          [5, 3],
          [5, 4],
          [5, 5],
          [6, 5],
          [6, 6],
          [5, 6],
          [4, 6],
          [3, 6],
          [2, 6],
          [1, 6],
          [0, 6],
        ],
      ],
      stops: [[4, 5], [6, 6]],
      facing: [[4, 5, "E"], [6, 6, "N"]],
      lamps: [[6, 5, 0]],
      levers: [[5, 1, "W"], [5, 5, "E"], [6, 5, "S"], [4, 1, "N"]],
      stems: [[5, 1, "S"], [5, 5, "N"], [6, 5, "W"], [4, 1, "E"]],
    },
  },
  {
    id: "8-8",
    name: "Junction Rush",
    rows: [".........", "......T..", ".........", "TTTT.TTTT", "TTTT.TTTT", "TTTT.TTTT", ".........", "........."],
    depots: [
      { at: [0, 1], dir: "E", trains: [0, 1, 0], start: 0, every: 5 },
      { at: [0, 7], dir: "E", trains: [2, 2], start: 2, every: 3 },
      { at: [4, 0], dir: "S", trains: [1], start: 3, every: 5 },
    ],
    stations: [{ at: [8, 7], dir: "W", color: 0 }, { at: [2, 7], dir: "N", color: 1 }, { at: [8, 2], dir: "W", color: 2 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 50,
    introTitle: "Junction rush",
    introText: "Sort, merge and pass, all through one gap.",
    solution: {
      paths: [
        [
          [0, 1],
          [1, 1],
          [1, 0],
          [2, 0],
          [3, 0],
          [3, 1],
          [4, 1],
          [4, 2],
          [4, 3],
          [4, 4],
          [4, 5],
          [4, 6],
          [5, 6],
          [6, 6],
          [7, 6],
          [7, 7],
          [8, 7],
        ],
        [
          [0, 1],
          [1, 1],
          [1, 0],
          [2, 0],
          [3, 0],
          [3, 1],
          [4, 1],
          [4, 2],
          [4, 3],
          [4, 4],
          [4, 5],
          [4, 6],
          [3, 6],
          [2, 6],
          [2, 7],
        ],
        [
          [0, 7],
          [1, 7],
          [1, 6],
          [2, 6],
          [3, 6],
          [4, 6],
          [4, 5],
          [4, 4],
          [4, 3],
          [4, 2],
          [5, 2],
          [6, 2],
          [7, 2],
          [8, 2],
        ],
        [[4, 0], [4, 1], [4, 2], [4, 3], [4, 4], [4, 5], [4, 6], [3, 6], [2, 6], [2, 7]],
      ],
      stops: [[1, 6]],
      facing: [[1, 6, "E"]],
      lamps: [[4, 6, 0]],
      levers: [[4, 2, "E"], [4, 6, "E"], [2, 6, "S"]],
      stems: [[4, 1, "S"], [4, 2, "S"], [4, 6, "N"], [2, 6, "E"]],
    },
  },
];
