// Line 6, Coal Line. Block signals with a timetable, generated with tools/lab/blockgen.ts
// (plan in tools/lab/blockplan.ts) and picked by hand.

import type { Stop } from "../levels";

export const COAL_LINE: Stop[] = [
  {
    id: "6-1",
    name: "Slow Train Coming",
    rows: ["TTTTTTTTTT", "T.TT..TT.T", "T........T", "T.TTTTTT.T", "TTTTTTTTTT"],
    depots: [
      { at: [0, 1], dir: "E", trains: [0], start: 0, every: 4, goods: true },
      { at: [9, 3], dir: "W", trains: [1, 1], start: 3, every: 4 },
    ],
    stations: [{ at: [9, 1], dir: "W", color: 0 }, { at: [0, 3], dir: "E", color: 1 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 36,
    introTitle: "Stuck behind",
    introText: "Goods trains move every other beat. Anything behind one waits, so let it go first or last.",
    solution: {
      paths: [
        [[0, 1], [1, 1], [1, 2], [2, 2], [3, 2], [4, 2], [5, 2], [6, 2], [7, 2], [8, 2], [8, 1], [9, 1]],
        [
          [9, 3],
          [8, 3],
          [8, 2],
          [7, 2],
          [6, 2],
          [5, 2],
          [5, 1],
          [4, 1],
          [4, 2],
          [3, 2],
          [2, 2],
          [1, 2],
          [1, 3],
          [0, 3],
        ],
      ],
      stops: [[5, 1], [4, 1], [3, 2]],
      facing: [[5, 1, "S"], [4, 1, "S"], [3, 2, "E"]],
      levers: [[1, 2, "S"], [4, 2, "E"], [5, 2, "N"], [8, 2, "N"]],
      stems: [[1, 2, "E"], [4, 2, "W"], [5, 2, "E"], [8, 2, "W"]],
    },
  },
  {
    id: "6-2",
    name: "Coal Drop",
    rows: ["TTTTTTTTTTT", "T.TT..TTT.T", "T.........T", "T.TTTTTTT.T", "TTTTTTTTTTT"],
    depots: [
      { at: [0, 1], dir: "E", trains: [0], start: 0, every: 4, goods: true },
      { at: [10, 3], dir: "W", trains: [1, 1], start: 2, every: 3 },
    ],
    stations: [{ at: [10, 1], dir: "W", color: 0 }, { at: [0, 3], dir: "E", color: 1 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 37,
    solution: {
      paths: [
        [[0, 1], [1, 1], [1, 2], [2, 2], [3, 2], [4, 2], [5, 2], [6, 2], [7, 2], [8, 2], [9, 2], [9, 1], [10, 1]],
        [
          [10, 3],
          [9, 3],
          [9, 2],
          [8, 2],
          [7, 2],
          [6, 2],
          [5, 2],
          [5, 1],
          [4, 1],
          [4, 2],
          [3, 2],
          [2, 2],
          [1, 2],
          [1, 3],
          [0, 3],
        ],
      ],
      stops: [[5, 1], [4, 1], [3, 2]],
      facing: [[5, 1, "S"], [4, 1, "S"], [3, 2, "E"]],
      levers: [[1, 2, "S"], [4, 2, "E"], [5, 2, "N"], [9, 2, "N"]],
      stems: [[1, 2, "E"], [4, 2, "W"], [5, 2, "E"], [9, 2, "W"]],
    },
  },
  {
    id: "6-3",
    name: "Pit Head",
    rows: ["TTTTTTTTTTT", "T.TTTTTTT.T", "T.........T", "T.T..TTTT.T", "TTTTTTTTTTT"],
    depots: [
      { at: [0, 1], dir: "E", trains: [0, 0], start: 0, every: 3 },
      { at: [10, 3], dir: "W", trains: [1, 1], start: 3, every: 4, goods: true },
    ],
    stations: [{ at: [10, 1], dir: "W", color: 0 }, { at: [0, 3], dir: "E", color: 1 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 48,
    solution: {
      paths: [
        [
          [0, 1],
          [1, 1],
          [1, 2],
          [2, 2],
          [3, 2],
          [3, 3],
          [4, 3],
          [4, 2],
          [5, 2],
          [6, 2],
          [7, 2],
          [8, 2],
          [9, 2],
          [9, 1],
          [10, 1],
        ],
        [[10, 3], [9, 3], [9, 2], [8, 2], [7, 2], [6, 2], [5, 2], [4, 2], [3, 2], [2, 2], [1, 2], [1, 3], [0, 3]],
      ],
      stops: [[3, 3], [4, 3]],
      facing: [[3, 3, "N"], [4, 3, "N"]],
      levers: [[1, 2, "S"], [3, 2, "S"], [4, 2, "W"], [9, 2, "N"]],
      stems: [[1, 2, "E"], [3, 2, "W"], [4, 2, "E"], [9, 2, "W"]],
    },
  },
  {
    id: "6-4",
    name: "Coke Ovens",
    rows: ["........", ".T......", "TTTTTT.T", "TTTTTT.T", "TTTTTT.T", "........", "........"],
    depots: [
      { at: [7, 1], dir: "W", trains: [0], start: 0, every: 4, goods: true },
      { at: [3, 6], dir: "N", trains: [1, 1], start: 3, every: 3 },
      { at: [5, 0], dir: "S", trains: [2], start: 4, every: 4 },
    ],
    stations: [{ at: [0, 6], dir: "E", color: 0 }, { at: [3, 0], dir: "S", color: 1 }, { at: [7, 6], dir: "W", color: 2 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 34,
    solution: {
      paths: [
        [
          [7, 1],
          [6, 1],
          [6, 2],
          [6, 3],
          [6, 4],
          [6, 5],
          [6, 6],
          [5, 6],
          [4, 6],
          [4, 5],
          [3, 5],
          [2, 5],
          [2, 6],
          [1, 6],
          [0, 6],
        ],
        [[3, 6], [3, 5], [4, 5], [5, 5], [6, 5], [6, 4], [6, 3], [6, 2], [6, 1], [5, 1], [4, 1], [3, 1], [3, 0]],
        [[5, 0], [5, 1], [6, 1], [6, 2], [6, 3], [6, 4], [6, 5], [6, 6], [7, 6]],
      ],
      stops: [[5, 5], [5, 6]],
      facing: [[5, 5, "E"], [5, 6, "E"]],
      lamps: [[6, 6, 0]],
      levers: [[6, 1, "W"], [6, 5, "S"], [6, 6, "W"], [4, 5, "E"], [3, 5, "W"], [5, 1, "W"]],
      stems: [[6, 1, "S"], [6, 5, "N"], [6, 6, "N"], [4, 5, "W"], [3, 5, "E"], [5, 1, "E"]],
    },
  },
  {
    id: "6-5",
    name: "Wagon Way",
    rows: ["TTT.TTTTTTTT", "T.T..TTTTT.T", "T..........T", "T.TTTTT..T.T", "TTTTTTTT.TTT"],
    depots: [
      { at: [0, 1], dir: "E", trains: [0], start: 0, every: 3, goods: true },
      { at: [11, 3], dir: "W", trains: [1, 1], start: 4, every: 4 },
      { at: [3, 0], dir: "S", trains: [2], start: 1, every: 4 },
    ],
    stations: [{ at: [11, 1], dir: "W", color: 0 }, { at: [0, 3], dir: "E", color: 1 }, { at: [8, 4], dir: "N", color: 2 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 37,
    solution: {
      paths: [
        [
          [0, 1],
          [1, 1],
          [1, 2],
          [2, 2],
          [3, 2],
          [3, 1],
          [4, 1],
          [4, 2],
          [5, 2],
          [6, 2],
          [7, 2],
          [8, 2],
          [9, 2],
          [10, 2],
          [10, 1],
          [11, 1],
        ],
        [
          [11, 3],
          [10, 3],
          [10, 2],
          [9, 2],
          [8, 2],
          [7, 2],
          [6, 2],
          [5, 2],
          [4, 2],
          [3, 2],
          [2, 2],
          [1, 2],
          [1, 3],
          [0, 3],
        ],
        [[3, 0], [3, 1], [4, 1], [4, 2], [5, 2], [6, 2], [7, 2], [8, 2], [8, 3], [8, 4]],
      ],
      stops: [[1, 1], [7, 2], [9, 2]],
      facing: [[1, 1, "S"], [7, 2, "E"], [9, 2, "W"]],
      lamps: [[8, 2, 0]],
      levers: [[1, 2, "S"], [3, 2, "N"], [4, 2, "W"], [8, 2, "E"], [10, 2, "N"]],
      stems: [[1, 2, "E"], [3, 2, "W"], [3, 1, "E"], [4, 2, "E"], [8, 2, "W"], [10, 2, "W"]],
    },
  },
  {
    id: "6-6",
    name: "Two Goods",
    rows: ["TTTTTTTTTTTT", "T.TTTTT..T.T", "T..........T", "T.T..TTTTT.T", "TTTTTTTTTTTT"],
    depots: [
      { at: [0, 1], dir: "E", trains: [0], start: 0, every: 4, goods: true },
      { at: [11, 3], dir: "W", trains: [1], start: 2, every: 4, goods: true },
    ],
    stations: [{ at: [11, 1], dir: "W", color: 0 }, { at: [0, 3], dir: "E", color: 1 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 38,
    solution: {
      paths: [
        [
          [0, 1],
          [1, 1],
          [1, 2],
          [2, 2],
          [3, 2],
          [4, 2],
          [5, 2],
          [6, 2],
          [7, 2],
          [7, 1],
          [8, 1],
          [8, 2],
          [9, 2],
          [10, 2],
          [10, 1],
          [11, 1],
        ],
        [
          [11, 3],
          [10, 3],
          [10, 2],
          [9, 2],
          [8, 2],
          [7, 2],
          [6, 2],
          [5, 2],
          [4, 2],
          [3, 2],
          [2, 2],
          [1, 2],
          [1, 3],
          [0, 3],
        ],
      ],
      stops: [[8, 1], [7, 1], [9, 2]],
      facing: [[8, 1, "W"], [7, 1, "S"], [9, 2, "W"]],
      levers: [[1, 2, "S"], [7, 2, "N"], [8, 2, "W"], [10, 2, "N"]],
      stems: [[1, 2, "E"], [7, 2, "W"], [8, 2, "E"], [10, 2, "W"]],
    },
  },
  {
    id: "6-7",
    name: "Slag Heap",
    rows: ["........", "....T...", "........", "TTTTTT.T", "TTTTTT.T", "TTTTTT.T", "........", "........"],
    depots: [
      { at: [2, 0], dir: "S", trains: [0], start: 0, every: 4, goods: true },
      { at: [0, 7], dir: "E", trains: [1, 1], start: 1, every: 3 },
      { at: [0, 2], dir: "E", trains: [2, 2], start: 4, every: 4 },
    ],
    stations: [{ at: [7, 7], dir: "W", color: 0 }, { at: [6, 0], dir: "S", color: 1 }, { at: [3, 7], dir: "N", color: 2 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 44,
    solution: {
      paths: [
        [
          [2, 0],
          [2, 1],
          [3, 1],
          [3, 0],
          [4, 0],
          [5, 0],
          [5, 1],
          [6, 1],
          [6, 2],
          [6, 3],
          [6, 4],
          [6, 5],
          [6, 6],
          [6, 7],
          [7, 7],
        ],
        [
          [0, 7],
          [1, 7],
          [1, 6],
          [2, 6],
          [3, 6],
          [4, 6],
          [5, 6],
          [6, 6],
          [6, 5],
          [6, 4],
          [6, 3],
          [6, 2],
          [6, 1],
          [6, 0],
        ],
        [
          [0, 2],
          [1, 2],
          [1, 1],
          [2, 1],
          [3, 1],
          [3, 2],
          [4, 2],
          [5, 2],
          [6, 2],
          [6, 3],
          [6, 4],
          [6, 5],
          [6, 6],
          [6, 7],
          [5, 7],
          [4, 7],
          [4, 6],
          [3, 6],
          [3, 7],
        ],
      ],
      stops: [[5, 6], [5, 7]],
      facing: [[5, 6, "E"], [5, 7, "E"]],
      lamps: [[3, 1, 0], [6, 7, 0]],
      levers: [[3, 1, "N"], [6, 1, "N"], [6, 2, "N"], [6, 6, "S"], [6, 7, "E"], [3, 6, "S"], [4, 6, "E"]],
      stems: [[2, 1, "E"], [3, 1, "W"], [6, 1, "S"], [6, 2, "S"], [6, 6, "N"], [6, 7, "N"], [3, 6, "E"], [4, 6, "W"]],
    },
  },
  {
    id: "6-8",
    name: "Coal Rush",
    rows: ["TTTTTTTTTTTTT", "T.TTTTTTTTT.T", "T...........T", "T.TTT...TTT.T", "TTTTTTTTTTTTT"],
    depots: [
      { at: [0, 1], dir: "E", trains: [0, 0], start: 0, every: 4, goods: true },
      { at: [12, 3], dir: "W", trains: [1, 1, 1], start: 1, every: 3 },
    ],
    stations: [{ at: [12, 1], dir: "W", color: 0 }, { at: [0, 3], dir: "E", color: 1 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 40,
    introTitle: "Coal rush",
    introText: "Coal one way, passengers the other.",
    solution: {
      paths: [
        [
          [0, 1],
          [1, 1],
          [1, 2],
          [2, 2],
          [3, 2],
          [4, 2],
          [5, 2],
          [6, 2],
          [7, 2],
          [8, 2],
          [9, 2],
          [10, 2],
          [11, 2],
          [11, 1],
          [12, 1],
        ],
        [
          [12, 3],
          [11, 3],
          [11, 2],
          [10, 2],
          [9, 2],
          [8, 2],
          [7, 2],
          [7, 3],
          [6, 3],
          [5, 3],
          [5, 2],
          [4, 2],
          [3, 2],
          [2, 2],
          [1, 2],
          [1, 3],
          [0, 3],
        ],
      ],
      stops: [[6, 2], [5, 3]],
      facing: [[6, 2, "W"], [5, 3, "N"]],
      levers: [[1, 2, "S"], [5, 2, "E"], [7, 2, "S"], [11, 2, "N"]],
      stems: [[1, 2, "E"], [5, 2, "W"], [7, 2, "E"], [11, 2, "W"]],
    },
  },
];
