// Line 5, Moor Line. Generated with tools/campaign and curated by hand.

import type { Stop } from "../levels";

export const MOOR_LINE: Stop[] = [
  {
    id: "5-1",
    name: "Single Line Working",
    rows: ["T.T.TT.T", ".....T..", "........", "....TT..", "T.TTT..T"],
    depots: [
      { at: [1, 4], dir: "N", trains: [0], every: 3, start: 0 },
      { at: [7, 1], dir: "W", trains: [1], every: 3, start: 0 },
    ],
    stations: [{ at: [6, 4], dir: "N", color: 0 }, { at: [0, 1], dir: "E", color: 1 }],
    allowStop: true,
    allowLamp: true,
    introTitle: "Take turns",
    introText: "One track, two directions. Let one train clear the line before the other sets off.",
    solution: {
      paths: [
        [[1, 4], [1, 3], [2, 3], [2, 2], [3, 2], [4, 2], [5, 2], [6, 2], [6, 3], [6, 4]],
        [[7, 1], [6, 1], [6, 2], [5, 2], [4, 2], [3, 2], [2, 2], [2, 1], [1, 1], [0, 1]],
      ],
      stops: [[1, 3], [2, 3]],
      levers: [[6, 2, "S"], [2, 2, "N"]],
    },
  },
  {
    id: "5-2",
    name: "Bog Cotton",
    rows: [".......", "....T..", "T......", "^^^^^..", "^^^^^TT", "......T", "..T....", "......."],
    depots: [
      { at: [0, 1], dir: "E", trains: [0], every: 3, start: 1 },
      { at: [2, 0], dir: "S", trains: [1], every: 3, start: 2 },
    ],
    stations: [{ at: [5, 0], dir: "S", color: 0 }, { at: [1, 7], dir: "N", color: 1 }],
    tunnels: [[[1, 3], [1, 4]]],
    allowStop: true,
    allowLamp: true,
    solution: {
      paths: [
        [[0, 1], [1, 1], [2, 1], [3, 1], [3, 2], [4, 2], [5, 2], [5, 1], [5, 0]],
        [[2, 0], [2, 1], [2, 2], [1, 2], [1, 3], [1, 4], [1, 5], [1, 6], [1, 7]],
      ],
      stops: [[1, 1]],
    },
  },
  {
    id: "5-3",
    name: "Grouse Butts",
    rows: ["~.~~.~.~", "........", "........", "...~....", "~.~~.~.~"],
    depots: [
      { at: [0, 2], dir: "E", trains: [0, 0], every: 4, start: 1 },
      { at: [7, 1], dir: "W", trains: [1, 1], every: 4, start: 1 },
    ],
    stations: [{ at: [6, 4], dir: "N", color: 0 }, { at: [1, 4], dir: "N", color: 1 }],
    allowStop: true,
    allowLamp: true,
    solution: {
      paths: [
        [[7, 1], [6, 1], [5, 1], [4, 1], [3, 1], [2, 1], [1, 1], [1, 2], [1, 3], [1, 4]],
        [[0, 2], [1, 2], [2, 2], [3, 2], [4, 2], [5, 2], [5, 3], [6, 3], [6, 4]],
      ],
    },
  },
  {
    id: "5-4",
    name: "Cairn Tunnel",
    rows: ["..TTTT..", "..T..T..", "........", "TT.^^^^^", ".T.^^^^^", "........", "........", "........"],
    depots: [
      { at: [4, 7], dir: "N", trains: [0, 1, 0], every: 3, start: 1 },
      { at: [1, 7], dir: "N", trains: [2], every: 3, start: 1 },
    ],
    stations: [{ at: [0, 1], dir: "E", color: 0 }, { at: [7, 1], dir: "W", color: 1 }, { at: [6, 7], dir: "N", color: 2 }],
    tunnels: [[[5, 3], [5, 4]]],
    allowStop: true,
    allowLamp: true,
    solution: {
      paths: [
        [[4, 7], [4, 6], [4, 5], [5, 5], [5, 4], [5, 3], [5, 2], [4, 2], [3, 2], [2, 2], [1, 2], [1, 1], [0, 1]],
        [[1, 7], [1, 6], [2, 6], [3, 6], [4, 6], [5, 6], [6, 6], [6, 7]],
        [[4, 7], [4, 6], [4, 5], [5, 5], [5, 4], [5, 3], [5, 2], [6, 2], [6, 1], [7, 1]],
      ],
      stops: [[2, 6]],
      lamps: [[5, 2, 0]],
      levers: [[5, 2, "W"]],
    },
  },
  {
    id: "5-5",
    name: "Peat Cutting",
    rows: [".....TTT", "......TT", "...T..T.", "........", "....^^..", "....^^..", "....^^TT", "....^^TT"],
    depots: [
      { at: [0, 3], dir: "E", trains: [0], every: 3, start: 2 },
      { at: [2, 7], dir: "N", trains: [1], every: 3, start: 1 },
      { at: [1, 0], dir: "S", trains: [2], every: 3, start: 3 },
    ],
    stations: [{ at: [7, 4], dir: "W", color: 0 }, { at: [4, 0], dir: "S", color: 1 }, { at: [0, 5], dir: "E", color: 2 }],
    tunnels: [[[4, 5], [5, 5]]],
    allowStop: true,
    allowLamp: true,
    solution: {
      paths: [
        [[1, 0], [1, 1], [1, 2], [1, 3], [1, 4], [1, 5], [0, 5]],
        [[2, 7], [2, 6], [2, 5], [3, 5], [3, 4], [3, 3], [4, 3], [4, 2], [4, 1], [4, 0]],
        [[0, 3], [1, 3], [2, 3], [3, 3], [3, 4], [3, 5], [4, 5], [5, 5], [6, 5], [6, 4], [7, 4]],
      ],
      stops: [[2, 3]],
      levers: [[3, 3, "E"], [3, 5, "E"]],
    },
  },
  {
    id: "5-6",
    name: "Two Way Moor",
    rows: ["T..TTTT.T", "......T..", ".........", "......T..", "T.T..TT.T"],
    depots: [
      { at: [0, 1], dir: "E", trains: [0, 0], every: 4, start: 2 },
      { at: [7, 4], dir: "N", trains: [1], every: 3, start: 3 },
    ],
    stations: [{ at: [7, 0], dir: "S", color: 0 }, { at: [1, 4], dir: "N", color: 1 }],
    allowStop: true,
    allowLamp: true,
    solution: {
      paths: [
        [[7, 4], [7, 3], [7, 2], [6, 2], [5, 2], [4, 2], [3, 2], [3, 3], [2, 3], [1, 3], [1, 4]],
        [[0, 1], [1, 1], [2, 1], [3, 1], [3, 2], [4, 2], [5, 2], [6, 2], [7, 2], [7, 1], [7, 0]],
      ],
      stops: [[2, 1], [3, 1]],
      levers: [[3, 2, "S"], [7, 2, "N"]],
    },
  },
  {
    id: "5-7",
    name: "Heather Bore",
    rows: ["TTT.....", "TTTT....", "T....T..", "....^^T.", ".TT.^^..", "..T.^^.T", "....^^TT", "....^^TT"],
    depots: [
      { at: [7, 1], dir: "W", trains: [0, 1], every: 4, start: 3 },
      { at: [5, 0], dir: "S", trains: [1, 0], every: 3, start: 3 },
    ],
    stations: [{ at: [1, 7], dir: "N", color: 0 }, { at: [0, 5], dir: "E", color: 1 }],
    tunnels: [[[4, 4], [5, 4]]],
    allowStop: true,
    allowLamp: true,
    solution: {
      paths: [
        [
          [7, 1],
          [6, 1],
          [6, 2],
          [7, 2],
          [7, 3],
          [7, 4],
          [6, 4],
          [5, 4],
          [4, 4],
          [3, 4],
          [3, 5],
          [3, 6],
          [2, 6],
          [1, 6],
          [1, 5],
          [0, 5],
        ],
        [
          [5, 0],
          [5, 1],
          [6, 1],
          [6, 2],
          [7, 2],
          [7, 3],
          [7, 4],
          [6, 4],
          [5, 4],
          [4, 4],
          [3, 4],
          [3, 5],
          [3, 6],
          [2, 6],
          [1, 6],
          [1, 5],
          [0, 5],
        ],
        [
          [7, 1],
          [6, 1],
          [6, 2],
          [7, 2],
          [7, 3],
          [7, 4],
          [6, 4],
          [5, 4],
          [4, 4],
          [3, 4],
          [3, 5],
          [3, 6],
          [2, 6],
          [1, 6],
          [1, 7],
        ],
        [
          [5, 0],
          [5, 1],
          [6, 1],
          [6, 2],
          [7, 2],
          [7, 3],
          [7, 4],
          [6, 4],
          [5, 4],
          [4, 4],
          [3, 4],
          [3, 5],
          [3, 6],
          [2, 6],
          [1, 6],
          [1, 7],
        ],
      ],
      stops: [[5, 1]],
      lamps: [[1, 6, 1]],
      levers: [[1, 6, "N"]],
    },
  },
  {
    id: "5-8",
    name: "Moor Rush",
    rows: ["TT....TT", "T......T", "........", "........", "TT....TT", "...^^...", "...^^...", "...^^...", "...^^..."],
    depots: [
      { at: [0, 3], dir: "E", trains: [0, 2, 0], every: 3, start: 2 },
      { at: [1, 8], dir: "N", trains: [1], every: 3, start: 2 },
      { at: [7, 7], dir: "W", trains: [2, 1], every: 4, start: 3 },
    ],
    stations: [{ at: [5, 0], dir: "S", color: 0 }, { at: [7, 5], dir: "W", color: 1 }, { at: [7, 2], dir: "W", color: 2 }],
    tunnels: [[[3, 7], [4, 7]]],
    allowStop: true,
    allowLamp: true,
    introTitle: "Moor rush",
    introText: "The tunnel is the quick way across. Everyone wants it.",
    solution: {
      paths: [
        [[1, 8], [1, 7], [2, 7], [3, 7], [4, 7], [5, 7], [6, 7], [6, 6], [6, 5], [7, 5]],
        [[7, 7], [6, 7], [6, 6], [6, 5], [7, 5]],
        [[0, 3], [1, 3], [2, 3], [2, 2], [2, 1], [3, 1], [4, 1], [5, 1], [5, 0]],
        [[7, 7], [6, 7], [6, 6], [6, 5], [5, 5], [5, 4], [5, 3], [5, 2], [6, 2], [7, 2]],
        [[0, 3], [1, 3], [2, 3], [2, 2], [2, 1], [3, 1], [4, 1], [5, 1], [5, 2], [6, 2], [7, 2]],
      ],
      stops: [[2, 7]],
      lamps: [[6, 5, 1], [5, 1, 0]],
      levers: [[6, 5, "E"], [5, 1, "N"]],
    },
  },
];
