// Line 9, Festival Line. Block signals with a timetable, generated with tools/lab/blockgen.ts
// (plan in tools/lab/blockplan.ts) and picked by hand.

import type { Stop } from "../levels";

export const FESTIVAL_LINE: Stop[] = [
  {
    id: "9-1",
    name: "Bunting",
    rows: ["........", "......H.", "........", "HHHHHH.H", "HHHHHH.H", "HHHHHH.H", "........", "........"],
    depots: [
      { at: [7, 2], dir: "W", trains: [0], start: 0, every: 5 },
      { at: [7, 7], dir: "W", trains: [1], start: 4, every: 4 },
      { at: [4, 0], dir: "S", trains: [2], start: 3, every: 5 },
      { at: [0, 7], dir: "E", trains: [3], start: 2, every: 5 },
    ],
    stations: [
      { at: [4, 7], dir: "N", color: 0 },
      { at: [0, 1], dir: "E", color: 1 },
      { at: [2, 7], dir: "N", color: 2 },
      { at: [2, 0], dir: "S", color: 3 },
    ],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 34,
    introTitle: "Fourth colour",
    introText: "Tangerine trains join in.",
    solution: {
      paths: [
        [[7, 2], [6, 2], [6, 3], [6, 4], [6, 5], [6, 6], [5, 6], [4, 6], [4, 7]],
        [
          [7, 7],
          [6, 7],
          [6, 6],
          [6, 5],
          [6, 4],
          [6, 3],
          [6, 2],
          [5, 2],
          [5, 1],
          [4, 1],
          [3, 1],
          [2, 1],
          [1, 1],
          [0, 1],
        ],
        [
          [4, 0],
          [4, 1],
          [4, 2],
          [5, 2],
          [6, 2],
          [6, 3],
          [6, 4],
          [6, 5],
          [6, 6],
          [5, 6],
          [4, 6],
          [3, 6],
          [2, 6],
          [2, 7],
        ],
        [
          [0, 7],
          [1, 7],
          [1, 6],
          [2, 6],
          [3, 6],
          [4, 6],
          [5, 6],
          [6, 6],
          [6, 5],
          [6, 4],
          [6, 3],
          [6, 2],
          [5, 2],
          [5, 1],
          [4, 1],
          [3, 1],
          [2, 1],
          [2, 0],
        ],
      ],
      stops: [[5, 1], [4, 2], [3, 6]],
      facing: [[5, 1, "S"], [4, 2, "E"], [3, 6, "E"]],
      lamps: [[4, 6, 0], [2, 1, 1]],
      levers: [[6, 2, "W"], [6, 6, "W"], [4, 6, "S"], [5, 2, "N"], [2, 1, "W"], [2, 6, "S"]],
      stems: [[6, 2, "S"], [6, 6, "N"], [4, 6, "E"], [5, 2, "E"], [2, 1, "E"], [2, 6, "E"]],
    },
  },
  {
    id: "9-2",
    name: "Bandstand",
    rows: ["HHH.HHHHHHHH", "H.H.HH...H.H", "H..........H", "H.HHHH.HHH.H", "HHHHHH.HHHHH"],
    depots: [
      { at: [0, 1], dir: "E", trains: [0, 0], start: 0, every: 4 },
      { at: [11, 3], dir: "W", trains: [1, 1], start: 3, every: 4 },
      { at: [6, 4], dir: "N", trains: [3], start: 1, every: 4 },
    ],
    stations: [{ at: [11, 1], dir: "W", color: 0 }, { at: [0, 3], dir: "E", color: 1 }, { at: [3, 0], dir: "S", color: 3 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 49,
    solution: {
      paths: [
        [
          [0, 1],
          [1, 1],
          [1, 2],
          [2, 2],
          [3, 2],
          [4, 2],
          [5, 2],
          [6, 2],
          [7, 2],
          [8, 2],
          [9, 2],
          [10, 2],
          [10, 1],
          [11, 1],
        ],
        [
          [11, 3],
          [10, 3],
          [10, 2],
          [9, 2],
          [8, 2],
          [7, 2],
          [6, 2],
          [5, 2],
          [4, 2],
          [3, 2],
          [2, 2],
          [1, 2],
          [1, 3],
          [0, 3],
        ],
        [[6, 4], [6, 3], [6, 2], [5, 2], [4, 2], [3, 2], [3, 1], [3, 0]],
      ],
      stops: [[6, 3], [10, 3]],
      facing: [[6, 3, "N"], [10, 3, "N"]],
      lamps: [[3, 2, 1]],
      levers: [[1, 2, "S"], [3, 2, "W"], [6, 2, "E"], [10, 2, "N"]],
      stems: [[1, 2, "E"], [3, 2, "E"], [6, 2, "W"], [10, 2, "W"]],
    },
  },
  {
    id: "9-3",
    name: "Four Ways",
    rows: ["........", "........", "........", "HHHH.HHH", "HHHH.HHH", "HHHH.HHH", "........", "........"],
    depots: [
      { at: [0, 2], dir: "E", trains: [0, 0], start: 0, every: 3 },
      { at: [5, 7], dir: "N", trains: [1], start: 2, every: 4 },
      { at: [3, 0], dir: "S", trains: [2], start: 2, every: 5 },
      { at: [7, 7], dir: "W", trains: [3], start: 4, every: 4 },
    ],
    stations: [
      { at: [2, 7], dir: "N", color: 0 },
      { at: [6, 0], dir: "S", color: 1 },
      { at: [0, 7], dir: "E", color: 2 },
      { at: [1, 0], dir: "S", color: 3 },
    ],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 51,
    solution: {
      paths: [
        [
          [0, 2],
          [1, 2],
          [1, 1],
          [2, 1],
          [3, 1],
          [4, 1],
          [4, 2],
          [4, 3],
          [4, 4],
          [4, 5],
          [4, 6],
          [3, 6],
          [2, 6],
          [2, 7],
        ],
        [[5, 7], [5, 6], [4, 6], [4, 5], [4, 4], [4, 3], [4, 2], [5, 2], [5, 1], [6, 1], [6, 0]],
        [[3, 0], [3, 1], [4, 1], [4, 2], [4, 3], [4, 4], [4, 5], [4, 6], [3, 6], [2, 6], [1, 6], [1, 7], [0, 7]],
        [
          [7, 7],
          [6, 7],
          [6, 6],
          [5, 6],
          [4, 6],
          [4, 5],
          [4, 4],
          [4, 3],
          [4, 2],
          [4, 1],
          [3, 1],
          [2, 1],
          [1, 1],
          [1, 0],
        ],
      ],
      stops: [[4, 1], [6, 6]],
      facing: [[4, 1, "S"], [6, 6, "W"]],
      lamps: [[4, 2, 1], [2, 6, 0]],
      levers: [[1, 1, "N"], [3, 1, "W"], [4, 2, "E"], [4, 6, "W"], [2, 6, "S"]],
      stems: [[1, 1, "E"], [3, 1, "E"], [4, 2, "S"], [4, 6, "N"], [2, 6, "E"], [5, 6, "W"]],
    },
  },
  {
    id: "9-4",
    name: "Carousel",
    rows: ["HHH.HHHHHHHH", "H.H.HH...H.H", "H..........H", "H.HHHH.HHH.H", "HHHHHH.HHHHH"],
    depots: [
      { at: [0, 1], dir: "E", trains: [3, 3], start: 0, every: 4 },
      { at: [11, 3], dir: "W", trains: [1, 1], start: 3, every: 4 },
      { at: [6, 4], dir: "N", trains: [2], start: 1, every: 4 },
    ],
    stations: [{ at: [11, 1], dir: "W", color: 3 }, { at: [0, 3], dir: "E", color: 1 }, { at: [3, 0], dir: "S", color: 2 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 49,
    solution: {
      paths: [
        [
          [0, 1],
          [1, 1],
          [1, 2],
          [2, 2],
          [3, 2],
          [4, 2],
          [5, 2],
          [6, 2],
          [7, 2],
          [8, 2],
          [9, 2],
          [10, 2],
          [10, 1],
          [11, 1],
        ],
        [
          [11, 3],
          [10, 3],
          [10, 2],
          [9, 2],
          [8, 2],
          [7, 2],
          [6, 2],
          [5, 2],
          [4, 2],
          [3, 2],
          [2, 2],
          [1, 2],
          [1, 3],
          [0, 3],
        ],
        [[6, 4], [6, 3], [6, 2], [5, 2], [4, 2], [3, 2], [3, 1], [3, 0]],
      ],
      stops: [[6, 3], [10, 3]],
      facing: [[6, 3, "N"], [10, 3, "N"]],
      lamps: [[3, 2, 1]],
      levers: [[1, 2, "S"], [3, 2, "W"], [6, 2, "E"], [10, 2, "N"]],
      stems: [[1, 2, "E"], [3, 2, "E"], [6, 2, "W"], [10, 2, "W"]],
    },
  },
  {
    id: "9-5",
    name: "Fireworks",
    rows: [".........", ".........", ".........", "HHH.HH.HH", "HHH.HH.HH", ".........", "...H...H.", "........."],
    depots: [
      { at: [8, 2], dir: "W", trains: [0, 0], start: 0, every: 5 },
      { at: [0, 6], dir: "E", trains: [1, 1], start: 4, every: 3 },
      { at: [0, 2], dir: "E", trains: [2], start: 2, every: 5 },
      { at: [4, 7], dir: "N", trains: [3], start: 4, every: 3 },
    ],
    stations: [
      { at: [6, 7], dir: "N", color: 0 },
      { at: [3, 0], dir: "S", color: 1 },
      { at: [2, 7], dir: "N", color: 2 },
      { at: [5, 0], dir: "S", color: 3 },
    ],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 25,
    solution: {
      paths: [
        [[8, 2], [7, 2], [6, 2], [6, 3], [6, 4], [6, 5], [6, 6], [6, 7]],
        [[0, 6], [1, 6], [2, 6], [2, 5], [3, 5], [3, 4], [3, 3], [3, 2], [3, 1], [3, 0]],
        [[0, 2], [1, 2], [1, 1], [2, 1], [3, 1], [3, 2], [3, 3], [3, 4], [3, 5], [2, 5], [2, 6], [2, 7]],
        [[4, 7], [4, 6], [4, 5], [5, 5], [6, 5], [6, 4], [6, 3], [6, 2], [6, 1], [5, 1], [5, 0]],
      ],
      stops: [[2, 1], [7, 2]],
      facing: [[2, 1, "E"], [7, 2, "W"]],
      levers: [[6, 2, "N"], [6, 5, "S"], [2, 6, "S"], [3, 1, "N"]],
      stems: [[6, 2, "S"], [6, 5, "N"], [2, 6, "N"], [3, 1, "S"]],
    },
  },
  {
    id: "9-6",
    name: "Ferris Wheel",
    rows: ["HHHHHHHH.HHHH", "H.HHHHHH.HH.H", "H...........H", "H.HH...HHHH.H", "HHHH.HHHHHHHH"],
    depots: [
      { at: [0, 1], dir: "E", trains: [0, 0], start: 0, every: 3 },
      { at: [12, 3], dir: "W", trains: [3, 3], start: 2, every: 4 },
      { at: [8, 0], dir: "S", trains: [2], start: 3, every: 3 },
    ],
    stations: [{ at: [12, 1], dir: "W", color: 0 }, { at: [0, 3], dir: "E", color: 3 }, { at: [4, 4], dir: "N", color: 2 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 32,
    solution: {
      paths: [
        [
          [0, 1],
          [1, 1],
          [1, 2],
          [2, 2],
          [3, 2],
          [4, 2],
          [5, 2],
          [6, 2],
          [7, 2],
          [8, 2],
          [9, 2],
          [10, 2],
          [11, 2],
          [11, 1],
          [12, 1],
        ],
        [
          [12, 3],
          [11, 3],
          [11, 2],
          [10, 2],
          [9, 2],
          [8, 2],
          [7, 2],
          [6, 2],
          [6, 3],
          [5, 3],
          [4, 3],
          [4, 2],
          [3, 2],
          [2, 2],
          [1, 2],
          [1, 3],
          [0, 3],
        ],
        [[8, 0], [8, 1], [8, 2], [7, 2], [6, 2], [6, 3], [5, 3], [4, 3], [4, 4]],
      ],
      stops: [[5, 2], [6, 3]],
      facing: [[5, 2, "E"], [6, 3, "N"]],
      lamps: [[4, 3, 3]],
      levers: [[1, 2, "S"], [4, 2, "E"], [6, 2, "S"], [8, 2, "E"], [11, 2, "N"], [4, 3, "N"]],
      stems: [[1, 2, "E"], [4, 2, "W"], [6, 2, "E"], [8, 2, "W"], [11, 2, "W"], [4, 3, "E"]],
    },
  },
  {
    id: "9-7",
    name: "Last Orders",
    rows: [".........", "....H....", ".........", "HHHHHH.HH", "HHHHHH.HH", ".........", ".H....H..", "........."],
    depots: [
      { at: [8, 2], dir: "W", trains: [0, 0], start: 0, every: 4 },
      { at: [5, 7], dir: "N", trains: [1, 1], start: 4, every: 4 },
      { at: [2, 0], dir: "S", trains: [3, 3], start: 3, every: 5 },
    ],
    stations: [{ at: [8, 6], dir: "W", color: 0 }, { at: [7, 0], dir: "S", color: 1 }, { at: [2, 7], dir: "N", color: 3 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 45,
    solution: {
      paths: [
        [[8, 2], [7, 2], [6, 2], [6, 3], [6, 4], [6, 5], [7, 5], [7, 6], [8, 6]],
        [[5, 7], [5, 6], [5, 5], [6, 5], [6, 4], [6, 3], [6, 2], [6, 1], [7, 1], [7, 0]],
        [
          [2, 0],
          [2, 1],
          [3, 1],
          [3, 0],
          [4, 0],
          [5, 0],
          [6, 0],
          [6, 1],
          [7, 1],
          [7, 2],
          [6, 2],
          [6, 3],
          [6, 4],
          [6, 5],
          [5, 5],
          [4, 5],
          [4, 6],
          [3, 6],
          [2, 6],
          [2, 7],
        ],
      ],
      stops: [[5, 6]],
      facing: [[5, 6, "N"]],
      lamps: [[6, 5, 0], [7, 1, 1]],
      levers: [[6, 2, "N"], [6, 5, "E"], [5, 5, "W"], [7, 1, "N"]],
      stems: [[7, 2, "W"], [6, 2, "S"], [6, 5, "N"], [5, 5, "E"], [6, 1, "E"], [7, 1, "W"]],
    },
  },
  {
    id: "9-8",
    name: "Festival Rush",
    rows: [".........", ".........", ".........", "HHHHH.HHH", "HHHHH.HHH", ".........", ".H.......", "........."],
    depots: [
      { at: [0, 2], dir: "E", trains: [0, 0], start: 0, every: 4 },
      { at: [4, 7], dir: "N", trains: [1, 1], start: 2, every: 4 },
      { at: [6, 0], dir: "S", trains: [2], start: 1, every: 3 },
      { at: [6, 7], dir: "N", trains: [3, 3], start: 2, every: 3 },
    ],
    stations: [
      { at: [8, 6], dir: "W", color: 0 },
      { at: [8, 1], dir: "W", color: 1 },
      { at: [2, 7], dir: "N", color: 2 },
      { at: [4, 0], dir: "S", color: 3 },
    ],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 56,
    introTitle: "Festival rush",
    introText: "Four colours and one way through.",
    solution: {
      paths: [
        [
          [0, 2],
          [1, 2],
          [1, 1],
          [1, 0],
          [2, 0],
          [3, 0],
          [3, 1],
          [4, 1],
          [5, 1],
          [5, 2],
          [5, 3],
          [5, 4],
          [5, 5],
          [6, 5],
          [7, 5],
          [7, 6],
          [8, 6],
        ],
        [[4, 7], [4, 6], [4, 5], [5, 5], [5, 4], [5, 3], [5, 2], [5, 1], [6, 1], [7, 1], [8, 1]],
        [
          [6, 0],
          [6, 1],
          [7, 1],
          [7, 2],
          [6, 2],
          [5, 2],
          [5, 3],
          [5, 4],
          [5, 5],
          [4, 5],
          [3, 5],
          [3, 6],
          [2, 6],
          [2, 7],
        ],
        [[6, 7], [6, 6], [6, 5], [5, 5], [5, 4], [5, 3], [5, 2], [5, 1], [4, 1], [4, 0]],
      ],
      stops: [[4, 6], [6, 6]],
      facing: [[4, 6, "N"], [6, 6, "N"]],
      lamps: [[5, 1, 1], [5, 5, 0], [7, 1, 1]],
      levers: [[4, 1, "N"], [5, 1, "E"], [5, 2, "N"], [5, 5, "E"], [6, 5, "E"], [4, 5, "W"], [7, 1, "E"]],
      stems: [[4, 1, "E"], [5, 1, "S"], [5, 2, "S"], [5, 5, "N"], [6, 5, "W"], [4, 5, "E"], [6, 1, "E"], [7, 1, "W"]],
    },
  },
];
