// Line 5, Moor Line. Block signals with a timetable, generated with tools/lab/blockgen.ts
// (plan in tools/lab/blockplan.ts) and picked by hand.

import type { Stop } from "../levels";

export const MOOR_LINE: Stop[] = [
  {
    id: "5-1",
    name: "Single Line Working",
    rows: ["TTTTTTTTTTTT", "T.TTTT..TT.T", "T..........T", "T.TTTTTTTT.T", "TTTTTTTTTTTT"],
    depots: [
      { at: [0, 1], dir: "E", trains: [0, 0], start: 0, every: 4 },
      { at: [11, 3], dir: "W", trains: [1, 1], start: 2, every: 3 },
    ],
    stations: [{ at: [11, 1], dir: "W", color: 0 }, { at: [0, 3], dir: "E", color: 1 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 40,
    introTitle: "Follow on",
    introText: "A long single line. A signal partway along lets a second train set off before the first is home.",
    solution: {
      paths: [
        [
          [0, 1],
          [1, 1],
          [1, 2],
          [2, 2],
          [3, 2],
          [4, 2],
          [5, 2],
          [6, 2],
          [6, 1],
          [7, 1],
          [7, 2],
          [8, 2],
          [9, 2],
          [10, 2],
          [10, 1],
          [11, 1],
        ],
        [
          [11, 3],
          [10, 3],
          [10, 2],
          [9, 2],
          [8, 2],
          [7, 2],
          [6, 2],
          [5, 2],
          [4, 2],
          [3, 2],
          [2, 2],
          [1, 2],
          [1, 3],
          [0, 3],
        ],
      ],
      stops: [[1, 1], [7, 1]],
      facing: [[1, 1, "S"], [7, 1, "S"]],
      levers: [[1, 2, "S"], [6, 2, "N"], [7, 2, "W"], [10, 2, "N"]],
      stems: [[1, 2, "E"], [6, 2, "W"], [7, 2, "E"], [10, 2, "W"]],
    },
  },
  {
    id: "5-2",
    name: "Bog Cotton",
    rows: ["TTTTTTTTTTTT", "T.TTTTTTTT.T", "T..........T", "T.T..TT..T.T", "TTTTTTTTTTTT"],
    depots: [
      { at: [0, 1], dir: "E", trains: [0, 0], start: 0, every: 4 },
      { at: [11, 3], dir: "W", trains: [1, 1], start: 2, every: 4 },
    ],
    stations: [{ at: [11, 1], dir: "W", color: 0 }, { at: [0, 3], dir: "E", color: 1 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 39,
    solution: {
      paths: [
        [
          [0, 1],
          [1, 1],
          [1, 2],
          [2, 2],
          [3, 2],
          [3, 3],
          [4, 3],
          [4, 2],
          [5, 2],
          [6, 2],
          [7, 2],
          [8, 2],
          [9, 2],
          [10, 2],
          [10, 1],
          [11, 1],
        ],
        [
          [11, 3],
          [10, 3],
          [10, 2],
          [9, 2],
          [8, 2],
          [7, 2],
          [6, 2],
          [5, 2],
          [4, 2],
          [3, 2],
          [2, 2],
          [1, 2],
          [1, 3],
          [0, 3],
        ],
      ],
      stops: [[3, 3], [4, 3]],
      facing: [[3, 3, "N"], [4, 3, "N"]],
      levers: [[1, 2, "S"], [3, 2, "S"], [4, 2, "W"], [10, 2, "N"]],
      stems: [[1, 2, "E"], [3, 2, "W"], [4, 2, "E"], [10, 2, "W"]],
    },
  },
  {
    id: "5-3",
    name: "Grouse Butts",
    rows: ["TTTTTTTTTTTT", "T.TTTTTTTT.T", "T..........T", "T.TTT...TT.T", "TTTTTTTTTTTT"],
    depots: [
      { at: [0, 1], dir: "E", trains: [0, 0, 0], start: 0, every: 4 },
      { at: [11, 3], dir: "W", trains: [1], start: 3, every: 3 },
    ],
    stations: [{ at: [11, 1], dir: "W", color: 0 }, { at: [0, 3], dir: "E", color: 1 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 29,
    solution: {
      paths: [
        [
          [0, 1],
          [1, 1],
          [1, 2],
          [2, 2],
          [3, 2],
          [4, 2],
          [5, 2],
          [6, 2],
          [7, 2],
          [8, 2],
          [9, 2],
          [10, 2],
          [10, 1],
          [11, 1],
        ],
        [
          [11, 3],
          [10, 3],
          [10, 2],
          [9, 2],
          [8, 2],
          [7, 2],
          [7, 3],
          [6, 3],
          [5, 3],
          [5, 2],
          [4, 2],
          [3, 2],
          [2, 2],
          [1, 2],
          [1, 3],
          [0, 3],
        ],
      ],
      stops: [[6, 2], [7, 3]],
      levers: [[1, 2, "S"], [5, 2, "E"], [7, 2, "S"], [10, 2, "N"]],
      stems: [[1, 2, "E"], [5, 2, "W"], [7, 2, "E"], [10, 2, "W"]],
    },
  },
  {
    id: "5-4",
    name: "Cairn Tunnel",
    rows: ["TTTTTTTTTTTT", "T.TTTTTTTT.T", "T..........T", "T.TTT..TTT.T", "TTTTTTTTTTTT"],
    depots: [
      { at: [0, 1], dir: "E", trains: [0, 0], start: 0, every: 3 },
      { at: [11, 3], dir: "W", trains: [1, 1], start: 3, every: 3 },
    ],
    stations: [{ at: [11, 1], dir: "W", color: 0 }, { at: [0, 3], dir: "E", color: 1 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 35,
    solution: {
      paths: [
        [
          [0, 1],
          [1, 1],
          [1, 2],
          [2, 2],
          [3, 2],
          [4, 2],
          [5, 2],
          [5, 3],
          [6, 3],
          [6, 2],
          [7, 2],
          [8, 2],
          [9, 2],
          [10, 2],
          [10, 1],
          [11, 1],
        ],
        [
          [11, 3],
          [10, 3],
          [10, 2],
          [9, 2],
          [8, 2],
          [7, 2],
          [6, 2],
          [5, 2],
          [4, 2],
          [3, 2],
          [2, 2],
          [1, 2],
          [1, 3],
          [0, 3],
        ],
      ],
      stops: [[5, 3], [6, 3]],
      facing: [[5, 3, "N"], [6, 3, "N"]],
      levers: [[1, 2, "S"], [5, 2, "S"], [6, 2, "W"], [10, 2, "N"]],
      stems: [[1, 2, "E"], [5, 2, "W"], [6, 2, "E"], [10, 2, "W"]],
    },
  },
  {
    id: "5-5",
    name: "Peat Cutting",
    rows: ["TTTTTTTTTTTTT", "T.TTTTT..TT.T", "T...........T", "T.T..TTTTTT.T", "TTTTTTTTTTTTT"],
    depots: [
      { at: [0, 1], dir: "E", trains: [0, 0], start: 0, every: 3 },
      { at: [12, 3], dir: "W", trains: [1, 1], start: 2, every: 3 },
    ],
    stations: [{ at: [12, 1], dir: "W", color: 0 }, { at: [0, 3], dir: "E", color: 1 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 39,
    solution: {
      paths: [
        [
          [0, 1],
          [1, 1],
          [1, 2],
          [2, 2],
          [3, 2],
          [3, 3],
          [4, 3],
          [4, 2],
          [5, 2],
          [6, 2],
          [7, 2],
          [8, 2],
          [9, 2],
          [10, 2],
          [11, 2],
          [11, 1],
          [12, 1],
        ],
        [
          [12, 3],
          [11, 3],
          [11, 2],
          [10, 2],
          [9, 2],
          [8, 2],
          [7, 2],
          [6, 2],
          [5, 2],
          [4, 2],
          [3, 2],
          [2, 2],
          [1, 2],
          [1, 3],
          [0, 3],
        ],
      ],
      stops: [[3, 3], [4, 3]],
      facing: [[3, 3, "N"], [4, 3, "N"]],
      levers: [[1, 2, "S"], [3, 2, "S"], [4, 2, "W"], [11, 2, "N"]],
      stems: [[1, 2, "E"], [3, 2, "W"], [4, 2, "E"], [11, 2, "W"]],
    },
  },
  {
    id: "5-6",
    name: "Two Way Moor",
    rows: ["TTTTTTTTTTTTT", "T.TTTT...TT.T", "T...........T", "T.TTTTTTTTT.T", "TTTTTTTTTTTTT"],
    depots: [
      { at: [0, 1], dir: "E", trains: [0, 0, 0], start: 0, every: 3 },
      { at: [12, 3], dir: "W", trains: [1, 1], start: 1, every: 3 },
    ],
    stations: [{ at: [12, 1], dir: "W", color: 0 }, { at: [0, 3], dir: "E", color: 1 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 32,
    solution: {
      paths: [
        [
          [0, 1],
          [1, 1],
          [1, 2],
          [2, 2],
          [3, 2],
          [4, 2],
          [5, 2],
          [6, 2],
          [6, 1],
          [7, 1],
          [8, 1],
          [8, 2],
          [9, 2],
          [10, 2],
          [11, 2],
          [11, 1],
          [12, 1],
        ],
        [
          [12, 3],
          [11, 3],
          [11, 2],
          [10, 2],
          [9, 2],
          [8, 2],
          [7, 2],
          [6, 2],
          [5, 2],
          [4, 2],
          [3, 2],
          [2, 2],
          [1, 2],
          [1, 3],
          [0, 3],
        ],
      ],
      stops: [[6, 1], [7, 2]],
      facing: [[6, 1, "S"], [7, 2, "W"]],
      levers: [[1, 2, "S"], [6, 2, "N"], [8, 2, "W"], [11, 2, "N"]],
      stems: [[1, 2, "E"], [6, 2, "W"], [8, 2, "E"], [11, 2, "W"]],
    },
  },
  {
    id: "5-7",
    name: "Heather Bore",
    rows: ["TTTTTTT.TTTTT", "T.TTTT...TT.T", "T...........T", "T.TTTTTTT.T.T", "TTTTTTTTT.TTT"],
    depots: [
      { at: [0, 1], dir: "E", trains: [0, 0], start: 0, every: 3 },
      { at: [12, 3], dir: "W", trains: [1, 1], start: 1, every: 3 },
      { at: [9, 4], dir: "N", trains: [2], start: 4, every: 3 },
    ],
    stations: [{ at: [12, 1], dir: "W", color: 0 }, { at: [0, 3], dir: "E", color: 1 }, { at: [7, 0], dir: "S", color: 2 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 29,
    solution: {
      paths: [
        [
          [0, 1],
          [1, 1],
          [1, 2],
          [2, 2],
          [3, 2],
          [4, 2],
          [5, 2],
          [6, 2],
          [6, 1],
          [7, 1],
          [8, 1],
          [8, 2],
          [9, 2],
          [10, 2],
          [11, 2],
          [11, 1],
          [12, 1],
        ],
        [
          [12, 3],
          [11, 3],
          [11, 2],
          [10, 2],
          [9, 2],
          [8, 2],
          [7, 2],
          [6, 2],
          [5, 2],
          [4, 2],
          [3, 2],
          [2, 2],
          [1, 2],
          [1, 3],
          [0, 3],
        ],
        [[9, 4], [9, 3], [9, 2], [8, 2], [8, 1], [7, 1], [7, 0]],
      ],
      stops: [[6, 1], [7, 2], [9, 3]],
      facing: [[6, 1, "S"], [7, 2, "W"], [9, 3, "N"]],
      lamps: [[8, 2, 1]],
      levers: [[1, 2, "S"], [6, 2, "N"], [7, 1, "N"], [8, 2, "W"], [9, 2, "E"], [11, 2, "N"]],
      stems: [[1, 2, "E"], [6, 2, "W"], [7, 1, "E"], [8, 2, "E"], [9, 2, "W"], [11, 2, "W"]],
    },
  },
  {
    id: "5-8",
    name: "Moor Rush",
    rows: ["TTTTTTTTTTTTT", "T.T...TTTTT.T", "T...........T", "T.TTTTTT..T.T", "TTTTTTTTTTTTT"],
    depots: [
      { at: [0, 1], dir: "E", trains: [0, 0, 0], start: 0, every: 4 },
      { at: [12, 3], dir: "W", trains: [1, 1, 1], start: 2, every: 3 },
    ],
    stations: [{ at: [12, 1], dir: "W", color: 0 }, { at: [0, 3], dir: "E", color: 1 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 46,
    introTitle: "Moor rush",
    introText: "The longest line yet, busy both ways.",
    solution: {
      paths: [
        [
          [0, 1],
          [1, 1],
          [1, 2],
          [2, 2],
          [3, 2],
          [4, 2],
          [5, 2],
          [6, 2],
          [7, 2],
          [8, 2],
          [9, 2],
          [10, 2],
          [11, 2],
          [11, 1],
          [12, 1],
        ],
        [
          [12, 3],
          [11, 3],
          [11, 2],
          [10, 2],
          [9, 2],
          [8, 2],
          [7, 2],
          [6, 2],
          [5, 2],
          [5, 1],
          [4, 1],
          [3, 1],
          [3, 2],
          [2, 2],
          [1, 2],
          [1, 3],
          [0, 3],
        ],
      ],
      stops: [[5, 1], [3, 1], [4, 2]],
      facing: [[5, 1, "S"], [3, 1, "S"]],
      levers: [[1, 2, "S"], [3, 2, "E"], [5, 2, "N"], [11, 2, "N"]],
      stems: [[1, 2, "E"], [3, 2, "W"], [5, 2, "E"], [11, 2, "W"]],
    },
  },
];
