// Line 7, Clockwork Line. Block signals with a timetable, generated with tools/lab/blockgen.ts
// (plan in tools/lab/blockplan.ts) and picked by hand.

import type { Stop } from "../levels";

export const CLOCKWORK_LINE: Stop[] = [
  {
    id: "7-1",
    name: "Not Before Ten",
    rows: ["TTTTTTTTTT", "T.TTTTTT.T", "T........T", "T.T..TTT.T", "TTTTTTTTTT"],
    depots: [
      { at: [0, 1], dir: "E", trains: [0, 0], start: 0, every: 3 },
      { at: [9, 3], dir: "W", trains: [1, 1], start: 1, every: 3 },
    ],
    stations: [{ at: [9, 1], dir: "W", color: 0 }, { at: [0, 3], dir: "E", color: 1 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 30,
    introTitle: "To the beat",
    introText: "From here the timetable gives you one beat to spare, not two.",
    solution: {
      paths: [
        [
          [0, 1],
          [1, 1],
          [1, 2],
          [2, 2],
          [3, 2],
          [3, 3],
          [4, 3],
          [4, 2],
          [5, 2],
          [6, 2],
          [7, 2],
          [8, 2],
          [8, 1],
          [9, 1],
        ],
        [[9, 3], [8, 3], [8, 2], [7, 2], [6, 2], [5, 2], [4, 2], [3, 2], [2, 2], [1, 2], [1, 3], [0, 3]],
      ],
      stops: [[3, 3], [4, 3]],
      facing: [[3, 3, "N"], [4, 3, "N"]],
      levers: [[1, 2, "S"], [3, 2, "S"], [4, 2, "W"], [8, 2, "N"]],
      stems: [[1, 2, "E"], [3, 2, "W"], [4, 2, "E"], [8, 2, "W"]],
    },
  },
  {
    id: "7-2",
    name: "Late Shift",
    rows: ["TTTTTTTTTTT", "T.TTTTTTT.T", "T.........T", "T.TTT..TT.T", "TTTTTTTTTTT"],
    depots: [
      { at: [0, 1], dir: "E", trains: [0, 0], start: 0, every: 3 },
      { at: [10, 3], dir: "W", trains: [1, 1], start: 1, every: 3 },
    ],
    stations: [{ at: [10, 1], dir: "W", color: 0 }, { at: [0, 3], dir: "E", color: 1 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 36,
    solution: {
      paths: [
        [
          [0, 1],
          [1, 1],
          [1, 2],
          [2, 2],
          [3, 2],
          [4, 2],
          [5, 2],
          [5, 3],
          [6, 3],
          [6, 2],
          [7, 2],
          [8, 2],
          [9, 2],
          [9, 1],
          [10, 1],
        ],
        [[10, 3], [9, 3], [9, 2], [8, 2], [7, 2], [6, 2], [5, 2], [4, 2], [3, 2], [2, 2], [1, 2], [1, 3], [0, 3]],
      ],
      stops: [[1, 1], [6, 3]],
      facing: [[1, 1, "S"], [6, 3, "N"]],
      levers: [[1, 2, "S"], [5, 2, "S"], [6, 2, "W"], [9, 2, "N"]],
      stems: [[1, 2, "E"], [5, 2, "W"], [6, 2, "E"], [9, 2, "W"]],
    },
  },
  {
    id: "7-3",
    name: "Platform Clock",
    rows: ["........", "........", "HHH.HHHH", "HHH.HHHH", "........", "..H..H..", "........"],
    depots: [
      { at: [0, 1], dir: "E", trains: [0, 0], start: 0, every: 5 },
      { at: [3, 6], dir: "N", trains: [1], start: 1, every: 3 },
      { at: [5, 0], dir: "S", trains: [2], start: 3, every: 5 },
    ],
    stations: [{ at: [6, 6], dir: "N", color: 0 }, { at: [7, 1], dir: "W", color: 1 }, { at: [0, 5], dir: "E", color: 2 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 28,
    solution: {
      paths: [
        [
          [0, 1],
          [1, 1],
          [1, 0],
          [2, 0],
          [3, 0],
          [3, 1],
          [3, 2],
          [3, 3],
          [3, 4],
          [4, 4],
          [5, 4],
          [6, 4],
          [6, 5],
          [6, 6],
        ],
        [[3, 6], [3, 5], [4, 5], [4, 4], [3, 4], [3, 3], [3, 2], [3, 1], [4, 1], [5, 1], [6, 1], [7, 1]],
        [[5, 0], [5, 1], [4, 1], [3, 1], [3, 2], [3, 3], [3, 4], [2, 4], [1, 4], [1, 5], [0, 5]],
      ],
      stops: [[4, 5]],
      facing: [[4, 5, "N"]],
      lamps: [[3, 4, 0]],
      levers: [[3, 1, "E"], [3, 4, "E"], [4, 4, "E"], [5, 1, "E"]],
      stems: [[3, 1, "S"], [3, 4, "N"], [4, 4, "W"], [5, 1, "W"]],
    },
  },
  {
    id: "7-4",
    name: "Half Past",
    rows: ["TTTTTTTTTTT", "T.TTT...T.T", "T.........T", "T.TTTTTTT.T", "TTTTTTTTTTT"],
    depots: [
      { at: [0, 1], dir: "E", trains: [0, 0, 0], start: 0, every: 4 },
      { at: [10, 3], dir: "W", trains: [1], start: 4, every: 3 },
    ],
    stations: [{ at: [10, 1], dir: "W", color: 0 }, { at: [0, 3], dir: "E", color: 1 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 25,
    solution: {
      paths: [
        [[0, 1], [1, 1], [1, 2], [2, 2], [3, 2], [4, 2], [5, 2], [6, 2], [7, 2], [8, 2], [9, 2], [9, 1], [10, 1]],
        [
          [10, 3],
          [9, 3],
          [9, 2],
          [8, 2],
          [7, 2],
          [7, 1],
          [6, 1],
          [5, 1],
          [5, 2],
          [4, 2],
          [3, 2],
          [2, 2],
          [1, 2],
          [1, 3],
          [0, 3],
        ],
      ],
      stops: [[7, 1], [6, 2]],
      levers: [[1, 2, "S"], [5, 2, "E"], [7, 2, "N"], [9, 2, "N"]],
      stems: [[1, 2, "E"], [5, 2, "W"], [7, 2, "E"], [9, 2, "W"]],
    },
  },
  {
    id: "7-5",
    name: "Escapement",
    rows: ["TTTTTT.TTTTT", "T.T....TTT.T", "T..........T", "T.TT.TTTTT.T", "TTTT.TTTTTTT"],
    depots: [
      { at: [0, 1], dir: "E", trains: [0, 0], start: 0, every: 4 },
      { at: [11, 3], dir: "W", trains: [1, 1], start: 1, every: 3 },
      { at: [4, 4], dir: "N", trains: [2], start: 3, every: 3 },
    ],
    stations: [{ at: [11, 1], dir: "W", color: 0 }, { at: [0, 3], dir: "E", color: 1 }, { at: [6, 0], dir: "S", color: 2 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 29,
    solution: {
      paths: [
        [
          [0, 1],
          [1, 1],
          [1, 2],
          [2, 2],
          [3, 2],
          [4, 2],
          [5, 2],
          [6, 2],
          [7, 2],
          [8, 2],
          [9, 2],
          [10, 2],
          [10, 1],
          [11, 1],
        ],
        [
          [11, 3],
          [10, 3],
          [10, 2],
          [9, 2],
          [8, 2],
          [7, 2],
          [6, 2],
          [6, 1],
          [5, 1],
          [4, 1],
          [3, 1],
          [3, 2],
          [2, 2],
          [1, 2],
          [1, 3],
          [0, 3],
        ],
        [[4, 4], [4, 3], [4, 2], [4, 1], [5, 1], [6, 1], [6, 0]],
      ],
      stops: [[5, 1], [5, 2], [4, 3]],
      facing: [[5, 1, "E"], [5, 2, "E"], [4, 3, "N"]],
      levers: [[1, 2, "S"], [3, 2, "E"], [6, 2, "N"], [10, 2, "N"], [6, 1, "N"], [4, 1, "W"]],
      stems: [[1, 2, "E"], [3, 2, "W"], [6, 2, "E"], [10, 2, "W"], [6, 1, "W"], [4, 1, "E"]],
    },
  },
  {
    id: "7-6",
    name: "Two Clocks",
    rows: ["........", "......H.", "........", "HHHHHH.H", "HHHHHH.H", "HHHHHH.H", "........", "........"],
    depots: [
      { at: [7, 2], dir: "W", trains: [0, 0], start: 0, every: 3 },
      { at: [0, 7], dir: "E", trains: [1, 1], start: 1, every: 3 },
      { at: [3, 0], dir: "S", trains: [2], start: 3, every: 5 },
    ],
    stations: [{ at: [6, 7], dir: "N", color: 0 }, { at: [5, 0], dir: "S", color: 1 }, { at: [4, 7], dir: "N", color: 2 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 31,
    solution: {
      paths: [
        [[7, 2], [6, 2], [6, 3], [6, 4], [6, 5], [6, 6], [6, 7]],
        [
          [0, 7],
          [1, 7],
          [1, 6],
          [2, 6],
          [2, 7],
          [3, 7],
          [3, 6],
          [4, 6],
          [5, 6],
          [6, 6],
          [6, 5],
          [6, 4],
          [6, 3],
          [6, 2],
          [5, 2],
          [5, 1],
          [5, 0],
        ],
        [[3, 0], [3, 1], [4, 1], [5, 1], [5, 2], [6, 2], [6, 3], [6, 4], [6, 5], [6, 6], [5, 6], [4, 6], [4, 7]],
      ],
      stops: [[4, 1]],
      facing: [[4, 1, "E"]],
      lamps: [[6, 6, 0]],
      levers: [[6, 2, "W"], [6, 6, "S"], [4, 6, "S"], [5, 1, "N"]],
      stems: [[6, 2, "S"], [6, 6, "N"], [4, 6, "E"], [5, 1, "S"]],
    },
  },
  {
    id: "7-7",
    name: "Pendulum",
    rows: ["TTTTTTTTTTTT", "T.TTTTT..T.T", "T..........T", "T.T..TTTTT.T", "TTTTTTTTTTTT"],
    depots: [
      { at: [0, 1], dir: "E", trains: [0, 0], start: 0, every: 4 },
      { at: [11, 3], dir: "W", trains: [1, 1], start: 1, every: 3 },
    ],
    stations: [{ at: [11, 1], dir: "W", color: 0 }, { at: [0, 3], dir: "E", color: 1 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 36,
    solution: {
      paths: [
        [
          [0, 1],
          [1, 1],
          [1, 2],
          [2, 2],
          [3, 2],
          [4, 2],
          [5, 2],
          [6, 2],
          [7, 2],
          [8, 2],
          [9, 2],
          [10, 2],
          [10, 1],
          [11, 1],
        ],
        [
          [11, 3],
          [10, 3],
          [10, 2],
          [9, 2],
          [8, 2],
          [8, 1],
          [7, 1],
          [7, 2],
          [6, 2],
          [5, 2],
          [4, 2],
          [3, 2],
          [2, 2],
          [1, 2],
          [1, 3],
          [0, 3],
        ],
      ],
      stops: [[8, 1], [7, 1]],
      facing: [[8, 1, "S"], [7, 1, "S"]],
      levers: [[1, 2, "S"], [7, 2, "E"], [8, 2, "N"], [10, 2, "N"]],
      stems: [[1, 2, "E"], [7, 2, "W"], [8, 2, "E"], [10, 2, "W"]],
    },
  },
  {
    id: "7-8",
    name: "Rush Hour Timetable",
    rows: ["TTTTTTTTTTTTT", "T.TTTTTTTTT.T", "T...........T", "T.TT..TT..T.T", "TTTTTTTTTTTTT"],
    depots: [
      { at: [0, 1], dir: "E", trains: [0, 0, 0], start: 0, every: 3 },
      { at: [12, 3], dir: "W", trains: [1, 1], start: 2, every: 3 },
    ],
    stations: [{ at: [12, 1], dir: "W", color: 0 }, { at: [0, 3], dir: "E", color: 1 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 41,
    introTitle: "Timetable",
    introText: "Every beat counts.",
    solution: {
      paths: [
        [
          [0, 1],
          [1, 1],
          [1, 2],
          [2, 2],
          [3, 2],
          [4, 2],
          [5, 2],
          [6, 2],
          [7, 2],
          [8, 2],
          [9, 2],
          [10, 2],
          [11, 2],
          [11, 1],
          [12, 1],
        ],
        [
          [12, 3],
          [11, 3],
          [11, 2],
          [10, 2],
          [9, 2],
          [9, 3],
          [8, 3],
          [8, 2],
          [7, 2],
          [6, 2],
          [5, 2],
          [4, 2],
          [3, 2],
          [2, 2],
          [1, 2],
          [1, 3],
          [0, 3],
        ],
      ],
      stops: [[8, 3], [9, 3]],
      facing: [[8, 3, "N"], [9, 3, "N"]],
      levers: [[1, 2, "S"], [8, 2, "E"], [9, 2, "S"], [11, 2, "N"]],
      stems: [[1, 2, "E"], [8, 2, "W"], [9, 2, "E"], [11, 2, "W"]],
    },
  },
];
