// Line 3, Harbour Line. Block signals with a timetable, generated with tools/lab/blockgen.ts
// (plan in tools/lab/blockplan.ts) and picked by hand.

import type { Stop } from "../levels";

export const HARBOUR_LINE: Stop[] = [
  {
    id: "3-1",
    name: "Double Hold",
    rows: ["~~~~~~~~~", "~.~~..~.~", "~.......~", "~.~~~~~.~", "~~~~~~~~~"],
    depots: [
      { at: [0, 1], dir: "E", trains: [0, 0], start: 0, every: 3 },
      { at: [8, 3], dir: "W", trains: [1], start: 4, every: 4 },
    ],
    stations: [{ at: [8, 1], dir: "W", color: 0 }, { at: [0, 3], dir: "E", color: 1 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 24,
    introTitle: "Passing places",
    introText: "One line, trains both ways. Wait in a bay while the others pass, and get everyone home in time.",
    solution: {
      paths: [
        [[0, 1], [1, 1], [1, 2], [2, 2], [3, 2], [4, 2], [5, 2], [6, 2], [7, 2], [7, 1], [8, 1]],
        [[8, 3], [7, 3], [7, 2], [6, 2], [5, 2], [4, 2], [3, 2], [2, 2], [1, 2], [1, 3], [0, 3]],
      ],
      stops: [[7, 3]],
      facing: [[7, 3, "N"]],
      levers: [[1, 2, "S"], [7, 2, "N"]],
      stems: [[1, 2, "E"], [7, 2, "W"]],
    },
  },
  {
    id: "3-2",
    name: "Ferry Crossing",
    rows: ["~~~~~~~~~", "~.~...~.~", "~.......~", "~.~~~~~.~", "~~~~~~~~~"],
    depots: [
      { at: [0, 1], dir: "E", trains: [0, 0], start: 0, every: 4 },
      { at: [8, 3], dir: "W", trains: [1, 1], start: 3, every: 4 },
    ],
    stations: [{ at: [8, 1], dir: "W", color: 0 }, { at: [0, 3], dir: "E", color: 1 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 24,
    solution: {
      paths: [
        [[0, 1], [1, 1], [1, 2], [2, 2], [3, 2], [3, 1], [4, 1], [5, 1], [5, 2], [6, 2], [7, 2], [7, 1], [8, 1]],
        [[8, 3], [7, 3], [7, 2], [6, 2], [5, 2], [4, 2], [3, 2], [2, 2], [1, 2], [1, 3], [0, 3]],
      ],
      stops: [[5, 1], [4, 2]],
      facing: [[5, 1, "S"], [4, 2, "E"]],
      levers: [[1, 2, "S"], [3, 2, "N"], [5, 2, "W"], [7, 2, "N"]],
      stems: [[1, 2, "E"], [3, 2, "W"], [5, 2, "E"], [7, 2, "W"]],
    },
  },
  {
    id: "3-3",
    name: "Shared Berth",
    rows: ["~~~~~~~~~~", "~.~~~~~~.~", "~........~", "~.~~...~.~", "~~~~~~~~~~"],
    depots: [
      { at: [0, 1], dir: "E", trains: [0, 0], start: 0, every: 3 },
      { at: [9, 3], dir: "W", trains: [1, 1], start: 3, every: 3 },
    ],
    stations: [{ at: [9, 1], dir: "W", color: 0 }, { at: [0, 3], dir: "E", color: 1 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 22,
    solution: {
      paths: [
        [[0, 1], [1, 1], [1, 2], [2, 2], [3, 2], [4, 2], [5, 2], [6, 2], [7, 2], [8, 2], [8, 1], [9, 1]],
        [
          [9, 3],
          [8, 3],
          [8, 2],
          [7, 2],
          [6, 2],
          [6, 3],
          [5, 3],
          [4, 3],
          [4, 2],
          [3, 2],
          [2, 2],
          [1, 2],
          [1, 3],
          [0, 3],
        ],
      ],
      stops: [[5, 2], [6, 3]],
      facing: [[5, 2, "E"], [6, 3, "N"]],
      levers: [[1, 2, "S"], [4, 2, "E"], [6, 2, "S"], [8, 2, "N"]],
      stems: [[1, 2, "E"], [4, 2, "W"], [6, 2, "E"], [8, 2, "W"]],
    },
  },
  {
    id: "3-4",
    name: "Quayside",
    rows: ["~~~~~.~~~~", "~.~~~..~.~", "~........~", "~.~.~~~~.~", "~~~.~~~~~~"],
    depots: [
      { at: [0, 1], dir: "E", trains: [0, 0], start: 0, every: 4 },
      { at: [9, 3], dir: "W", trains: [1], start: 3, every: 4 },
      { at: [5, 0], dir: "S", trains: [2], start: 2, every: 3 },
    ],
    stations: [{ at: [9, 1], dir: "W", color: 0 }, { at: [0, 3], dir: "E", color: 1 }, { at: [3, 4], dir: "N", color: 2 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 32,
    solution: {
      paths: [
        [[0, 1], [1, 1], [1, 2], [2, 2], [3, 2], [4, 2], [5, 2], [6, 2], [7, 2], [8, 2], [8, 1], [9, 1]],
        [[9, 3], [8, 3], [8, 2], [7, 2], [6, 2], [5, 2], [4, 2], [3, 2], [2, 2], [1, 2], [1, 3], [0, 3]],
        [[5, 0], [5, 1], [5, 2], [4, 2], [3, 2], [3, 3], [3, 4]],
      ],
      stops: [[5, 1], [8, 3]],
      facing: [[5, 1, "S"], [8, 3, "N"]],
      lamps: [[3, 2, 1]],
      levers: [[1, 2, "S"], [3, 2, "W"], [5, 2, "E"], [8, 2, "N"]],
      stems: [[1, 2, "E"], [3, 2, "E"], [5, 2, "W"], [8, 2, "W"]],
    },
  },
  {
    id: "3-5",
    name: "Pier Queue",
    rows: ["~~~~~~~~~~~", "~.~~~~~~~.~", "~.........~", "~.~~~...~.~", "~~~~~~~~~~~"],
    depots: [
      { at: [0, 1], dir: "E", trains: [0, 0, 0], start: 0, every: 3 },
      { at: [10, 3], dir: "W", trains: [1], start: 4, every: 3 },
    ],
    stations: [{ at: [10, 1], dir: "W", color: 0 }, { at: [0, 3], dir: "E", color: 1 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 26,
    solution: {
      paths: [
        [[0, 1], [1, 1], [1, 2], [2, 2], [3, 2], [4, 2], [5, 2], [6, 2], [7, 2], [8, 2], [9, 2], [9, 1], [10, 1]],
        [
          [10, 3],
          [9, 3],
          [9, 2],
          [8, 2],
          [7, 2],
          [7, 3],
          [6, 3],
          [5, 3],
          [5, 2],
          [4, 2],
          [3, 2],
          [2, 2],
          [1, 2],
          [1, 3],
          [0, 3],
        ],
      ],
      stops: [[6, 2], [7, 3]],
      levers: [[1, 2, "S"], [5, 2, "E"], [7, 2, "S"], [9, 2, "N"]],
      stems: [[1, 2, "E"], [5, 2, "W"], [7, 2, "E"], [9, 2, "W"]],
    },
  },
  {
    id: "3-6",
    name: "Lighthouse",
    rows: ["~~~~~~~~~~~", "~.~~~~~~~.~", "~.........~", "~.~~~...~.~", "~~~~~~~~~~~"],
    depots: [
      { at: [0, 1], dir: "E", trains: [0, 0], start: 0, every: 3 },
      { at: [10, 3], dir: "W", trains: [1, 1], start: 3, every: 3 },
    ],
    stations: [{ at: [10, 1], dir: "W", color: 0 }, { at: [0, 3], dir: "E", color: 1 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 23,
    solution: {
      paths: [
        [[0, 1], [1, 1], [1, 2], [2, 2], [3, 2], [4, 2], [5, 2], [6, 2], [7, 2], [8, 2], [9, 2], [9, 1], [10, 1]],
        [
          [10, 3],
          [9, 3],
          [9, 2],
          [8, 2],
          [7, 2],
          [7, 3],
          [6, 3],
          [5, 3],
          [5, 2],
          [4, 2],
          [3, 2],
          [2, 2],
          [1, 2],
          [1, 3],
          [0, 3],
        ],
      ],
      stops: [[6, 2], [7, 3]],
      facing: [[6, 2, "E"], [7, 3, "N"]],
      levers: [[1, 2, "S"], [5, 2, "E"], [7, 2, "S"], [9, 2, "N"]],
      stems: [[1, 2, "E"], [5, 2, "W"], [7, 2, "E"], [9, 2, "W"]],
    },
  },
  {
    id: "3-7",
    name: "Tide Table",
    rows: ["~~~~~.~~~~~", "~.~~~.~~~.~", "~.........~", "~.~...~~~.~", "~~~.~~~~~~~"],
    depots: [
      { at: [0, 1], dir: "E", trains: [0, 0], start: 0, every: 4 },
      { at: [10, 3], dir: "W", trains: [1], start: 2, every: 3 },
      { at: [5, 0], dir: "S", trains: [2], start: 4, every: 4 },
    ],
    stations: [{ at: [10, 1], dir: "W", color: 0 }, { at: [0, 3], dir: "E", color: 1 }, { at: [3, 4], dir: "N", color: 2 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 34,
    solution: {
      paths: [
        [[0, 1], [1, 1], [1, 2], [2, 2], [3, 2], [4, 2], [5, 2], [6, 2], [7, 2], [8, 2], [9, 2], [9, 1], [10, 1]],
        [[10, 3], [9, 3], [9, 2], [8, 2], [7, 2], [6, 2], [5, 2], [4, 2], [3, 2], [2, 2], [1, 2], [1, 3], [0, 3]],
        [[5, 0], [5, 1], [5, 2], [4, 2], [3, 2], [3, 3], [3, 4]],
      ],
      stops: [[5, 1], [9, 3]],
      facing: [[5, 1, "S"], [9, 3, "N"]],
      lamps: [[3, 2, 1]],
      levers: [[1, 2, "S"], [3, 2, "W"], [5, 2, "E"], [9, 2, "N"]],
      stems: [[1, 2, "E"], [3, 2, "E"], [5, 2, "W"], [9, 2, "W"]],
    },
  },
  {
    id: "3-8",
    name: "Harbour Rush",
    rows: ["~~~~~~.~~~~~", "~.~~~~...~.~", "~..........~", "~.~..~.~~~.~", "~~~~~~.~~~~~"],
    depots: [
      { at: [0, 1], dir: "E", trains: [0, 0], start: 0, every: 3 },
      { at: [11, 3], dir: "W", trains: [1, 1], start: 1, every: 4 },
      { at: [6, 0], dir: "S", trains: [2], start: 2, every: 3 },
    ],
    stations: [{ at: [11, 1], dir: "W", color: 0 }, { at: [0, 3], dir: "E", color: 1 }, { at: [6, 4], dir: "N", color: 2 }],
    allowStop: true,
    allowLamp: true,
    signals: "block",
    deadline: 38,
    introTitle: "Harbour rush",
    introText: "A long quay, three lines and two bays.",
    solution: {
      paths: [
        [
          [0, 1],
          [1, 1],
          [1, 2],
          [2, 2],
          [3, 2],
          [3, 3],
          [4, 3],
          [4, 2],
          [5, 2],
          [6, 2],
          [7, 2],
          [8, 2],
          [9, 2],
          [10, 2],
          [10, 1],
          [11, 1],
        ],
        [
          [11, 3],
          [10, 3],
          [10, 2],
          [9, 2],
          [8, 2],
          [7, 2],
          [6, 2],
          [5, 2],
          [4, 2],
          [3, 2],
          [2, 2],
          [1, 2],
          [1, 3],
          [0, 3],
        ],
        [[6, 0], [6, 1], [6, 2], [6, 3], [6, 4]],
      ],
      stops: [[3, 3], [4, 3]],
      facing: [[3, 3, "N"], [4, 3, "N"]],
      levers: [[1, 2, "S"], [3, 2, "S"], [4, 2, "W"], [10, 2, "N"]],
      stems: [[1, 2, "E"], [3, 2, "W"], [4, 2, "E"], [10, 2, "W"]],
    },
  },
];
