// Difficulty prototypes for playtesting, at #/lab/1 and on. Not part of the campaign: nothing
// here is saved as stars or counted in progress. Generated by tools/lab/build.ts.

import type { LevelData } from "./puzzle";

export type LabStop = LevelData & { id: string; name: string };

export const LAB: LabStop[] = [
  {
    "id": "lab-1",
    "name": "Waiting Room",
    "rows": [
      "TTTTTTTTT",
      "D.T...T.S",
      "T.......T",
      "S.TTTTT.D",
      "TTTTTTTTT"
    ],
    "depots": [
      {
        "at": [
          0,
          1
        ],
        "dir": "E",
        "trains": [
          0,
          0
        ],
        "start": 0,
        "every": 3
      },
      {
        "at": [
          8,
          3
        ],
        "dir": "W",
        "trains": [
          1,
          1
        ],
        "start": 3,
        "every": 3
      }
    ],
    "stations": [
      {
        "at": [
          8,
          1
        ],
        "dir": "W",
        "color": 0
      },
      {
        "at": [
          0,
          3
        ],
        "dir": "E",
        "color": 1
      }
    ],
    "allowStop": true,
    "introTitle": "Prototype: single line",
    "introText": "One line, trains both ways. They can only pass where you make room.",
    "par": 14,
    "solution": {
      "paths": [
        [
          [
            0,
            1
          ],
          [
            1,
            1
          ],
          [
            1,
            2
          ],
          [
            2,
            2
          ],
          [
            3,
            2
          ],
          [
            3,
            1
          ],
          [
            4,
            1
          ],
          [
            5,
            1
          ],
          [
            5,
            2
          ],
          [
            6,
            2
          ],
          [
            7,
            2
          ],
          [
            7,
            1
          ],
          [
            8,
            1
          ]
        ],
        [
          [
            8,
            3
          ],
          [
            7,
            3
          ],
          [
            7,
            2
          ],
          [
            6,
            2
          ],
          [
            5,
            2
          ],
          [
            4,
            2
          ],
          [
            3,
            2
          ],
          [
            2,
            2
          ],
          [
            1,
            2
          ],
          [
            1,
            3
          ],
          [
            0,
            3
          ]
        ]
      ],
      "stops": [
        [
          3,
          1
        ],
        [
          4,
          1
        ]
      ],
      "levers": [
        [
          1,
          2,
          "S"
        ],
        [
          3,
          2,
          "N"
        ],
        [
          5,
          2,
          "W"
        ],
        [
          7,
          2,
          "N"
        ]
      ],
      "stems": [
        [
          1,
          2,
          "E"
        ],
        [
          3,
          2,
          "W"
        ],
        [
          5,
          2,
          "E"
        ],
        [
          7,
          2,
          "W"
        ]
      ]
    }
  },
  {
    "id": "lab-2",
    "name": "Passing Time",
    "rows": [
      "TTTTTTTTT",
      "D.T...T.S",
      "T.......T",
      "S.TTTTT.D",
      "TTTTTTTTT"
    ],
    "depots": [
      {
        "at": [
          0,
          1
        ],
        "dir": "E",
        "trains": [
          0,
          0
        ],
        "start": 0,
        "every": 4
      },
      {
        "at": [
          8,
          3
        ],
        "dir": "W",
        "trains": [
          1,
          1
        ],
        "start": 2,
        "every": 4
      }
    ],
    "stations": [
      {
        "at": [
          8,
          1
        ],
        "dir": "W",
        "color": 0
      },
      {
        "at": [
          0,
          3
        ],
        "dir": "E",
        "color": 1
      }
    ],
    "allowStop": true,
    "introTitle": "Prototype: single line, new timetable",
    "introText": "The same line with a different timetable.",
    "par": 14,
    "solution": {
      "paths": [
        [
          [
            0,
            1
          ],
          [
            1,
            1
          ],
          [
            1,
            2
          ],
          [
            2,
            2
          ],
          [
            3,
            2
          ],
          [
            3,
            1
          ],
          [
            4,
            1
          ],
          [
            5,
            1
          ],
          [
            5,
            2
          ],
          [
            6,
            2
          ],
          [
            7,
            2
          ],
          [
            7,
            1
          ],
          [
            8,
            1
          ]
        ],
        [
          [
            8,
            3
          ],
          [
            7,
            3
          ],
          [
            7,
            2
          ],
          [
            6,
            2
          ],
          [
            5,
            2
          ],
          [
            4,
            2
          ],
          [
            3,
            2
          ],
          [
            2,
            2
          ],
          [
            1,
            2
          ],
          [
            1,
            3
          ],
          [
            0,
            3
          ]
        ]
      ],
      "stops": [
        [
          3,
          1
        ],
        [
          4,
          1
        ],
        [
          4,
          2
        ]
      ],
      "levers": [
        [
          1,
          2,
          "S"
        ],
        [
          3,
          2,
          "N"
        ],
        [
          5,
          2,
          "W"
        ],
        [
          7,
          2,
          "N"
        ]
      ],
      "stems": [
        [
          1,
          2,
          "E"
        ],
        [
          3,
          2,
          "W"
        ],
        [
          5,
          2,
          "E"
        ],
        [
          7,
          2,
          "W"
        ]
      ]
    }
  },
  {
    "id": "lab-3",
    "name": "Two Bays",
    "rows": [
      "TTTTTTTTTTTTT",
      "D.T..TTT..T.S",
      "T...........T",
      "S.TTTTTTTTT.D",
      "TTTTTTTTTTTTT"
    ],
    "depots": [
      {
        "at": [
          0,
          1
        ],
        "dir": "E",
        "trains": [
          0,
          0
        ],
        "start": 0,
        "every": 3
      },
      {
        "at": [
          12,
          3
        ],
        "dir": "W",
        "trains": [
          1,
          1
        ],
        "start": 2,
        "every": 3
      }
    ],
    "stations": [
      {
        "at": [
          12,
          1
        ],
        "dir": "W",
        "color": 0
      },
      {
        "at": [
          0,
          3
        ],
        "dir": "E",
        "color": 1
      }
    ],
    "allowStop": true,
    "introTitle": "Prototype: where to pass",
    "introText": "A long single line with room to pass in two places. Pick the right one.",
    "par": 17,
    "solution": {
      "paths": [
        [
          [
            0,
            1
          ],
          [
            1,
            1
          ],
          [
            1,
            2
          ],
          [
            2,
            2
          ],
          [
            3,
            2
          ],
          [
            4,
            2
          ],
          [
            5,
            2
          ],
          [
            6,
            2
          ],
          [
            7,
            2
          ],
          [
            8,
            2
          ],
          [
            9,
            2
          ],
          [
            10,
            2
          ],
          [
            11,
            2
          ],
          [
            11,
            1
          ],
          [
            12,
            1
          ]
        ],
        [
          [
            12,
            3
          ],
          [
            11,
            3
          ],
          [
            11,
            2
          ],
          [
            10,
            2
          ],
          [
            9,
            2
          ],
          [
            9,
            1
          ],
          [
            8,
            1
          ],
          [
            8,
            2
          ],
          [
            7,
            2
          ],
          [
            6,
            2
          ],
          [
            5,
            2
          ],
          [
            4,
            2
          ],
          [
            3,
            2
          ],
          [
            2,
            2
          ],
          [
            1,
            2
          ],
          [
            1,
            3
          ],
          [
            0,
            3
          ]
        ]
      ],
      "stops": [
        [
          9,
          1
        ],
        [
          8,
          1
        ]
      ],
      "levers": [
        [
          1,
          2,
          "S"
        ],
        [
          8,
          2,
          "E"
        ],
        [
          9,
          2,
          "N"
        ],
        [
          11,
          2,
          "N"
        ]
      ],
      "stems": [
        [
          1,
          2,
          "E"
        ],
        [
          8,
          2,
          "W"
        ],
        [
          9,
          2,
          "E"
        ],
        [
          11,
          2,
          "W"
        ]
      ]
    }
  },
  {
    "id": "lab-4",
    "name": "One Bridge",
    "rows": [
      ".........",
      ".........",
      ".........",
      "~~~~.~~~~",
      "~~~~.~~~~",
      ".........",
      ".........",
      "........."
    ],
    "depots": [
      {
        "at": [
          0,
          1
        ],
        "dir": "E",
        "trains": [
          0,
          0
        ],
        "start": 0,
        "every": 5
      },
      {
        "at": [
          8,
          6
        ],
        "dir": "W",
        "trains": [
          1,
          1
        ],
        "start": 3,
        "every": 3
      },
      {
        "at": [
          8,
          1
        ],
        "dir": "W",
        "trains": [
          2,
          2
        ],
        "start": 2,
        "every": 5
      }
    ],
    "stations": [
      {
        "at": [
          0,
          6
        ],
        "dir": "E",
        "color": 0
      },
      {
        "at": [
          4,
          0
        ],
        "dir": "S",
        "color": 1
      },
      {
        "at": [
          4,
          7
        ],
        "dir": "N",
        "color": 2
      }
    ],
    "allowStop": true,
    "allowLamp": true,
    "introTitle": "Prototype: one bridge",
    "introText": "Three lines and one bridge, with traffic both ways.",
    "par": 20,
    "solution": {
      "paths": [
        [
          [
            0,
            1
          ],
          [
            1,
            1
          ],
          [
            2,
            1
          ],
          [
            3,
            1
          ],
          [
            4,
            1
          ],
          [
            4,
            2
          ],
          [
            4,
            3
          ],
          [
            4,
            4
          ],
          [
            4,
            5
          ],
          [
            4,
            6
          ],
          [
            3,
            6
          ],
          [
            2,
            6
          ],
          [
            1,
            6
          ],
          [
            0,
            6
          ]
        ],
        [
          [
            8,
            6
          ],
          [
            7,
            6
          ],
          [
            6,
            6
          ],
          [
            5,
            6
          ],
          [
            5,
            5
          ],
          [
            4,
            5
          ],
          [
            4,
            4
          ],
          [
            4,
            3
          ],
          [
            4,
            2
          ],
          [
            4,
            1
          ],
          [
            4,
            0
          ]
        ],
        [
          [
            8,
            1
          ],
          [
            7,
            1
          ],
          [
            6,
            1
          ],
          [
            5,
            1
          ],
          [
            5,
            2
          ],
          [
            4,
            2
          ],
          [
            4,
            3
          ],
          [
            4,
            4
          ],
          [
            4,
            5
          ],
          [
            4,
            6
          ],
          [
            4,
            7
          ]
        ]
      ],
      "stops": [
        [
          7,
          6
        ],
        [
          6,
          6
        ],
        [
          5,
          6
        ],
        [
          5,
          5
        ]
      ],
      "lamps": [
        [
          4,
          6,
          0
        ]
      ],
      "levers": [
        [
          4,
          1,
          "N"
        ],
        [
          4,
          2,
          "N"
        ],
        [
          4,
          5,
          "S"
        ],
        [
          4,
          6,
          "W"
        ]
      ],
      "stems": [
        [
          4,
          1,
          "S"
        ],
        [
          4,
          2,
          "S"
        ],
        [
          4,
          5,
          "N"
        ],
        [
          4,
          6,
          "N"
        ]
      ]
    }
  }
];
